exports.greetings = [
    'Hello',
    'Welcome',
    'Howdy',
    'Aloha',
    'Salutations',
    'Hello, nice to meet you',
    "What's up",
    'Yo',
    'Hiya',
    "Pleased to make your acquaintances",
    "A pleasure to meet you",
    "How's it hanging",
    "What's happening",
    "Yay! I'm glad you joined",
    "Am I glad to see you",
    "Hey",
    "Ahoy-hoy",
    "Oh wow...hello,",
    "Thanks for joining the server",
    "I'm glad you're here",
    "You made it",
    "Hello there",
    'Hello, nice to see you',
    'Thank you for joining',
    'Make yourself at home',
    'Mi casa es su casa'
];