exports.starter = [
    "I feel like",
    "I'm",
    "I love",
    "Here I go again",
    "I can't stop",
    "I'm addicted to",
    "I have fun",
    "I got caught",
    "I spend all my time",
    "My dog saw me",
    "I never get sick of",
    "I spend all my time",
    "My grandma walked in on me",
    "The police officer saw me",
    "A scary clown was watching me",
    "I really enjoy",
    "I spend hours and hours",
    "I got fired for",
    "I got in trouble for",
    "I got high fived in court for",
    "I got sent to jail for",
    "It was worth going blind for",
    "In the bathroom at work someone walked in on this guy",
    "The manager at the restaurant was caught",
    "I saw my boss",
    "They saw our boss",
    "Even my grandpa likes",
    "Late at night, I find myself",
    "Instead of studying, I am",
    "I couldn't believe it when my neighbor was",
    "During the family reunion, my cousin started",
    "My best friend's parents were shocked when they found us",
    "Imagine my surprise when I walked in on my teacher",
    "Caught red-handed while",
    "Online, I've become obsessed with",
    "I tried hiding it, but everyone found out I was",
    "My partner walked in while I was",
    "On vacation, we couldn't stop",
    "My roommate and I bonded over",
    "Who would have thought I'd end up",
    "At the library, I was secretly",
    "An awkward moment during dinner when I started",
    "I even dream about",
    "No one would guess I secretly love",
    "My guilty pleasure is",
    "In the middle of a meeting, I started",
    "I once turned a first date into",
    "Lost in thought, I accidentally began",
    "Right in the middle of the airport, I began",
    "During a road trip, my friends and I decided to try",
    "Spicing up a party by",
    "Late-night grocery shopping turned into",
    "Caught off guard when my Uber driver started",
    "A hilarious mix-up when I thought someone said to start",
    "Waiting for the bus, I passed the time by",
    "Who knew that a boring conference could lead to",
    "An unforgettable experience when I farted and then began",
    "No one could have predicted that they would begin",
    "Trying to impress my date by",
    "My family was shocked when I announced my love for",
    "In the middle of the park, a stranger and I started",
    "Never thought I'd find myself",
    "My friends dared me to try",
    "A surprise twist when the movie inspired us to furtively start",
    "My first time",
    "An impromptu moment when I overcorrected in my car while",
    "My coworkers and I started a new trend by",
    "A memorable wedding reception after",
    "Visiting a new city, I discovered a new type of guy while",
    "An interesting conversation starter when I mentioned",
    "Confronted by my parents about",
    "An unexpected turn of events led to",
    "Spicing up game night by",
    "The best part of the weekend was",
    "I never thought I'd have so much fun",
    "An unforgettable holiday when we were",
    "An odd hobby I picked up is",
    "An unusual bonding experience was when my friends and I practiced",
    "Laughing so hard we came when we were",
    "A memorable camping trip after",
    "In the middle of a concert, we decided to secretly try",
    "The craziest night of my life involved",
    "I had an unexpected adventure at Disney World while",
    "Things took a wild turn when we were",
    "An impulsive decision that led to my arrest was publicly",
    "An amusing misunderstanding while",
    "A random act of kindness turned into",
    "Adding excitement to my daily routine by",
    "The delivery driver saw me",

];



exports.jackingOff = [
    "cutting a hole in my jorts in order to jerk my gerkin without people noticin",
    "cutting a hole in my jorts in order to jerk my gerkin without people noticin",
    "cutting a hole in my jorts in order to jerk my gerkin without people noticin",
    "cutting a hole in my jorts in order to jerk my gerkin without people noticin",
    "Going on a big date with Rosy Palms",
    "Adjusting my set",
    "Applying the slimy hand brake",
    "Attacking the one-eyed purple-headed warrior",
    "Auditioning the finger puppets",
    "Auditioning my hand puppet",
    "A round of backstroke roulette",
    "Bashing the Bishop",
    "Bashing the candle",
    "Beating off",
    "Beating the balogna",
    "Beating the bed flute",
    "Beating the Bishop",
    "Beating the dummy",
    "Beating the old man",
    "Beating the pud",
    "Beating the stick",
    "Beating my meat",
    "A plate of Beef-stroke-it-off",
    "Being a virtuoso of the skin flute",
    "Being my own best friend",
    "Biffing off",
    "Bleeding the weed",
    "Blowing the load",
    "Blowing my own horn",
    "Bludgeoning the beefsteak",
    "Bobbing my boloney",
    "Bopping Richard",
    "Bopping the bishop",
    "Bopping the bolgney",
    "Bopping the Bonzo",
    "Boxing the bald champ",
    "Boxing the clown",
    "Boxing the jesuit and getting cockroaches",
    "Boxing with Richard",
    "Buffing the bishop",
    "Buffing the banana",
    "Buffing the rifle",
    "Buggering my hand",
    "Burping the baby",
    "Burping the worm",
    "Buttering the corn",
    "Caning the vandal",
    "Capturing the bishop",
    "Charming the snake",
    "Checking for testicular cancer",
    "Cheesing off",
    "Choking Kojak",
    "Choking the bald guy until he pukes",
    "Choking the chicken",
    "Choking the sheriff and waiting for the posse to come",
    "Churning my butter",
    "Clamping the pipe",
    "Cleaning my rifle",
    "Clearing the snorkel",
    "Climbing the tree",
    "Climbing Mount Baldy",
    "Clobbering the Kleenex",
    "A game of Closet Frisbee",
    "Clubbing the clam",
    "Coating Prince William Sound with love oil",
    "Coming into my own",
    "Coming to grips with myself",
    "Cooking the cream of cock",
    "Corralling the tadpoles",
    "A Game of Couch hockey for one",
    "Cranking the love pump",
    "Cranking the angry monkey",
    "Cranking the slippery shank",
    "Crimping the floppy wire",
    "Crowning the drowsy king",
    "Cuddlin' the sour Kielbasa",
    "Cuffing the skinny carrot",
    "Dancing with Johnnie One-Eye",
    "Dating Miss Michigan",
    "Dating Rosie Palm and her five sisters",
    "Decongesting the weasel",
    "Defrosting the fridge",
    "Diddling",
    "Digging for change",
    "Digitally oscillating one's penis",
    "Doin' The Solitary Rhumba",
    "Doing a solo hand job",
    "Doing battle with the Purple Helmeted Warrior of Love",
    "Doing handiwork",
    "Doing It my Way",
    "Doing the five-knuckle shuffle",
    "Doing the human version of AUTOEXEC.BAT",
    "Doing the janitor thing",
    "Doing the knuckle shuffle on the ol' piss pump",
    "Doing the pork sword jiggle",
    "Doing the White Knuckler",
    "Doing my own thing",
    "Downing at the club (for members only)",
    "Draining the monster",
    "Draining the poisons from the building",
    "Driving the skin bus",
    "Dry humping the ottoman",
    "Dundering the devil-dolphin",
    "Electing the president",
    "Engaging in safe sex",
    "Escorting the one-eyed postal worker out of its denim cell",
    "Faxing Jimmy Dean",
    "Faxing the Pope",
    "Feeding the ducks",
    "Firing the flesh musket",
    "Firing the Surgeon General",
    "Fishing for zipper trout",
    "Fisting my mister",
    "Some Five-finger solo",
    "Five-knuckle-shuffle on the old piss pump",
    "A Little Five on one",
    "Flicking on over the thumb",
    "Flapping Takkie ",
    "Flaying the Emperor",
    "Flicking the bic",
    "Flipping the Bishop",
    "Flogging the bishop",
    "Flogging the dog",
    "Flogging the dolphin",
    "Flogging the dong",
    "Flogging the frog",
    "Flogging the hog",
    "Flogging the log",
    "Flogging the mule",
    "Flogging the salami",
    "Flogging my dumber brother",
    "A Flute solo",
    "Fly fishing",
    "Fondling the fig",
    "Freeing Willy",
    "Frosting the pastries",
    "Galloping the antelope",
    "Galloping the old lizard",
    "Genitalic stimulation via phallengetic motion",
    "Getting a date with Slick Mittens",
    "Getting a grip on things",
    "Getting a stiffy",
    "Getting chafed",
    "Getting off",
    "Getting the German soldier marching",
    "Getting the glue stick",
    "Getting to know myself",
    "Getting my palm read by Mister Softee",
    "Getting my palm red",
    "Getting my pole varnished",
    "Giving it a tug",
    "Giving myself a low five",
    "Glazing the donut",
    "Going a couple of rounds with ol' josh",
    "Going blind",
    "Going on a date with Handrea and Palmela",
    "Going on a date with Rosey Palm and the five daughters",
    "Going on Peewee's little adventure",
    "Grappling the gorilla",
    "Greasing the pipe",
    "Gripping the pencil",
    "Hacking the hog",
    "Hand Shandy",
    "Handy work",
    "Hanging the old man",
    "Hard labor",
    "Having a ball",
    "Having a conversation with the one-eyed trouser snake",
    "Having a date with Fisty Palmer",
    "Having a date with Rosie Palm and her five sisters",
    "Having a ham shank",
    "Having a J. Arthur",
    "Having a one-night-stand with myself",
    "Having a Sherman",
    "Having a tug",
    "Having a tug-of-war with the cyclops",
    "Having an arm-wrestle with my one-eyed vessel",
    "Having dinner",
    "Having it off",
    "Having sex with someone you love",
    "Hitchhiking to heaven",
    "Hitchhiking underneath the big top",
    "Holding my own",
    "Holding the sausage hostage",
    "Honing the cone",
    "Hugging the hog",
    "Humping the hose",
    "Ironing some wrinkles",
    "Jack hammering",
    "Jacking off",
    "Jazzing myself",
    "Jerkin' the gherkin",
    "Jerking Jamby",
    "Jerking off",
    "Jerking the turkey",
    "Jerking yanking daisy-chaining",
    "Jizzlobbing",
    "Juggling the coullions",
    "Just jerkin' it",
    "Kicking seamen",
    "Kicking my roommate out for five to ten minutes to 'call my parents'",
    "Killing it",
    "Kneading my knockwurst",
    "Knuckle shuffle on the ol' piss pump",
    "Knuckling the bone",
    "La veuve poignet",
    "Launching the hand shuttle",
    "Looking for ticks",
    "Loping the mule",
    "Loving the muppet",
    "Lubing the Tube",
    "Making a foreskin cone",
    "Making friends with Big Ed",
    "Making instant pudding",
    "Making the bald man puke",
    "Making the scene with the magazine",
    "Making vanilla jism shakes",
    "Making myself at home",
    "Mangling the midget",
    "Manipulating the mango",
    "Manning the cockpit",
    "Manual labor",
    "Manual override",
    "Master bacon",
    "Meeting Mary Palm and her five sisters",
    "Meeting Rosie Hancock",
    "Meeting with Mother Thumb and her four daughters",
    "Milking one's self",
    "Milking the bull",
    "Milking the cow",
    "Milking the lizard",
    "Milking the moose",
    "Milking the weasel",
    "Minding my own business",
    "Molesting the mole",
    "Mounting a corporal and four",
    "Much goo about nothing",
    "Nerking my throbber",
    "Oiling the glove",
    "Onan's Olympics",
    "Onanism",
    "Blasting a One gun salute",
    "A One man show",
    "One off the wrist",
    "Packing my palm",
    "Paddling the pickle",
    "Painting the ceiling",
    "Painting the pickle",
    "Painting the walls",
    "Palming the calm",
    "Peelin' some chiles",
    "Peeling the banana",
    "Peeling the carrot",
    "Performing a self-test",
    "Performing diagnostics on my ManTool",
    "Perling the oyster",
    "Petting the lizard",
    "Phoning the czar",
    "Pipping the pumpkin",
    "Playing a little five-on-one",
    "Playing a one-stringed guitar",
    "Playing in a one-man show",
    "Playing Peek-A-Boo With Mr. Johnson",
    "Playing peekaboo",
    "Playing pocket pinball",
    "Playing pocket pool",
    "Playing tag with the pink torpedo",
    "Playing the flesh flute",
    "Playing the one-stringed melody",
    "Playing the skin flute",
    "Playing tug-o-war with the cyclops",
    "Playing Uno",
    "Playing with the spitting llama",
    "Playing with my turtle",
    "Pleasing my pisser",
    "Plunking my twanger",
    "Some Pocket pinball",
    "Some Pocket pool",
    "Pole vaulting",
    "Polishing Percy in my palm",
    "Polishing the beak",
    "Polishing the family jewels",
    "Polishing the helmet",
    "Polishing the rocket",
    "Polishing the sword",
    "Popping a nut",
    "Popping the cork",
    "Pounding off",
    "Pounding the bald-headed moose",
    "Pounding the pud",
    "Pounding my flounder",
    "Preparing the carrot",
    "Priming the pump",
    "Pud wrestling",
    "Pulling off",
    "Pulling rank",
    "Pulling the bologna pony",
    "Pulling the carrot",
    "Pulling the Colonel Sanders Heimleich Manuever",
    "Pulling the cord",
    "Pulling the five-knuckle shuffle",
    "Pulling the goalie",
    "Pulling the handbrake",
    "Pulling the pole",
    "Pulling the Pope",
    "Pulling the weed",
    "Pulling the wire",
    "Pulling my goalie",
    "Pulling my own leg",
    "Pulling my prick",
    "Pulling my pud",
    "Pulling my taffy",
    "Pummeling the priest",
    "Pumping cream",
    "Pumping the electric goo gun",
    "Pumping the gas at the self-service island",
    "Pumping the python",
    "Pumping the stump",
    "Punchin' the munchkin",
    "Punching the clown",
    "Punching the munchin",
    "Punishing Percy in the palm",
    "Punishing the Pope",
    "Qualifying in the testicular time trial",
    "Raising the mainsail",
    "Ramming the ham",
    "Rapid one arm pull-ups",
    "Reading poetry",
    "Relieving tension",
    "Riding the great white knuckler",
    "Rolling my own",
    "Romancing the bone",
    "Romeo and Himself",
    "Roping the pony",
    "Roping the Pope",
    "Roughing up the suspect",
    "Rubbing off",
    "Rubbing one out",
    "Rubbing the magic one-eyed wonder weasel",
    "Rubbing the pink eraser",
    "Rubbing the rod",
    "Running off a batch by hand",
    "Running the cheeta",
    "Sacrificing sperm to the god of lonely nights",
    "Sanding wood",
    "Saying a private prayer in the Church of the First Holy Monkey",
    "playing Schnauzer Shuffleboard",
    "Scouring the tower of power",
    "Scraping my horn",
    "Scratchin the itch",
    "Se faire les cinq doigts de la main",
    "A Secret handshake",
    "Engaging in Self abuse",
    "A little Self-induced penile regurgitation",
    "Some Self-inflicted intercourse",
    "Shaking hands with Abraham Lincoln",
    "Shaking hands with Jack McNasty",
    "Shaking hands with Mr. Happy",
    "Shaking Hands with Mr. President",
    "Shaking hands with the general",
    "Shaking hands with the midget",
    "Shaking hands with the unemployed",
    "Shaking hands with the wife's best friend",
    "Shaking hands with my John Thomas",
    "Shaking hands with my wife's best friend",
    "Shaking hands with Yul Brenner",
    "Shaking the bottle",
    "Shaking the dice",
    "Shaking the hand of the self-employed",
    "Shaking the sauce",
    "Shaking the sausage",
    "Shaking the snake",
    "Shanking",
    "Shellacking the shellaleigh",
    "Shemping the hog",
    "Shifting gears",
    "Shining the helmet",
    "Shining the pork sword",
    "Shining my pole",
    "Shooting skeet",
    "Shooting flies",
    "Shooting for the moon",
    "Shooting putty at the moon",
    "Shooting tadpoles at the moon",
    "Shooting my wad",
    "Shucking my corn",
    "Slaking the bacon",
    "Slamming the ham",
    "Slamming the hammer",
    "Slamming the salami",
    "Slamming the salmon",
    "Slamming the spam",
    "Slapping the big-nosed Rasta man",
    "Slappin the purple headed yogurt pistol",
    "Slapping high fives with Yul Brynner",
    "Slapping it",
    "Slapping pappy",
    "Slapping the carrot",
    "Slapping the clown",
    "Slapping the donkey",
    "Slapping the FleshGopher",
    "Slapping the pud",
    "Slapping the salami",
    "Sliding up and down my tube",
    "Slinging the jelly",
    "Smacking the oompa loompa",
    "Smacking the salami",
    "Smacking the weasel",
    "Smacking-off",
    "Snapping one off",
    "Snapping the carrot",
    "Snapping the monkey",
    "Snapping the rubber",
    "Snapping the whip",
    "A Solo flight",
    "A Solo marathon",
    "Some Solo sex",
    "Spanking Cheetah",
    "Spanking Elvis",
    "Spanking Frank",
    "Spanking the bishop",
    "Spanking the monkey",
    "Spanking the salami",
    "Spanking the wank",
    "Spit-polishing the purple helmet",
    "Spunking",
    "Squeezing the cheese",
    "Squeezing the cream from the flesh Twinkie",
    "Squeezing the juice",
    "Squeezing the lemon",
    "Squeezing the weasel",
    "Squeezing my cheese-dog",
    "A little Stinky pinky",
    "Stirring the batter",
    "Stirring the yogurt",
    "Strainin' the main vein",
    "Strangling the Serpent",
    "Striking the pink match",
    "Stroking it",
    "Stroking off",
    "Stroking the dog",
    "Stroking the lizard",
    "Stroking the mole",
    "Stroking the one-eyed burping gecko",
    "Stroking the satin-headed serpent",
    "Stroking the squirmin' German",
    "Stroking the wiener",
    "Stroking my poker",
    "Stroking my twinkie",
    "Taking a nap",
    "Taking a shake break",
    "Taking Herman to the circus",
    "Taking matters into my own hands",
    "Taking ol' one eye through the fly",
    "Taking part in population control",
    "Taking some time off",
    "Taking the Jocelyn Elders Midterm",
    "Taking the monster for a one-armed ride",
    "Talking quietly to myself",
    "Taming the shrew",
    "Taunting the one-eyed weasel",
    "Teasing the weasel",
    "Teasing the weenie",
    "Tenderizing the meat",
    "Tenderizing the tube steak",
    "A Testicular tensile strength test",
    "Testing the testicles",
    "Testing my batteries",
    "That crazy hand jive",
    "The art of Unisex",
    "The Colonel Sanders Heimleich Maneuver",
    "The five knuckle shuffle on the old piss pipe",
    "Thrapping",
    "Throwing",
    "Throwing one",
    "Thumping the pump",
    "Ticklewigglejigglepickle",
    "Tickling my fancy",
    "Tickling the ivory",
    "Tickling the one-eyed weasel",
    "Tickling the pickle",
    "Tonking",
    "Torkin' the fork",
    "Torturing the tentacle",
    "Tossing off",
    "Tossing the salad",
    "Tossing the snag",
    "Tossing the turkey",
    "Tossing yogurt",
    "Treating myself right",
    "Trouser snake CPR",
    "Tugging the slug",
    "Tugging the tapioca tube",
    "Tuning my horn",
    "Turning Japanese",
    "Twanging the wire",
    "Tweaking my twinkie",
    "Twisting my crank",
    "Twisting my tool",
    "Unloading the gun",
    "Using the Force on Darth Vader",
    "Varnishing the flagpole",
    "Violating the hedge-hog",
    "Visiting Rosy Palm and her five daughters",
    "Wacking off",
    "Wacking the one-eyed worm",
    "Wacking the weasel",
    "Wacking the willie",
    "Waking the dead",
    "Waking Wee Willie Wonka",
    "Walking the dog",
    "Walking the plank",
    "Walking the snake",
    "Waltzing with Willy",
    "Wanking",
    "Wanking with the one-eyed wonder weasel",
    "Washing the meat",
    "Waving the Magic Wand",
    "Waxing the car",
    "Waxing the carrot",
    "Waxing the dolphin",
    "Waxing my surfboard",
    "Whackin the weasel",
    "Whacking it",
    "Whacking off",
    "Whacking Willy",
    "Whipping off",
    "Whipping the bishop",
    "Whipping the dummy",
    "Whipping the one-eyed trouser snake",
    "Whipping the rat",
    "Whipping the stiff",
    "Whipping the wire",
    "Whipping up some sour cream",
    "Whipping willy the one-eyed wonder-worm",
    "Whipping my dripper",
    "White-water wristing",
    "Whittling the stick",
    "Whizzing jism",
    "Windsurfing on Mount Baldy",
    "Wonking my conker",
    "Wonking my donk",
    "Workin' out a stiff joint",
    "Working off",
    "Working off a batch",
    "Wrestling the eel",
    "Wrestling the one-eyed monster",
    "Wrestling the purple headed warrior",
    "Wrestling with the bald champ",
    "Wringing out my rope",
    "doing Wrist aerobics",
    "Yanking off",
    "Yanking the crank",
    "Yanking the yoyo",
    "Yanking my plank",
    "Boxing my clown",
    "Punching the munchkin",
    "Wanking",
    "Polishing my sword",
    "Some Backstroke roulette",
    "Bashing the candle",
    "Tipping off the inspector",
    "Tossing the snag",
    "Tossing the turkey",
    "Tossing yogurt",
    "Tugging the slug",
    "Twanging the wire",
    "Tweaking my Twinkie",
    "Twisting my crank",
    "Unleashing the alabaster yak",
    "Unloading the gun",
    "Unpacking the moving van",
    "Varnishing the flagpole",
    "Varnishing the banister",
    "Visiting with Papa Smurf",
    "Waking the dead",
    "Walking the dog",
    "Walking the plank",
    "Walking a mile in Mr. Wigglies shoes",
    "Wallowing in self pity",
    "Wanking with the one-eyed wonder weasel",
    "Washing the meat",
    "Waxing the Buick",
    "Waxing the carrot",
    "Waxing the dolphin",
    "Waxin n Milkin",
    "Whacking it",
    "Whacking the weasel",
    "Whacking my Willy",
    "Whipping the dummy",
    "Whipping the one-eyed trouser snake",
    "Whipping the one-eyed worm",
    "Whipping the rat",
    "Whipping the stiff",
    "Whipping the wire",
    "Whipping up some sour cream",
    "Whipping my dripper",
    "Whitewashing with Huck and Tom",
    "Whittling the stick",
    "Wiggling my walrus",
    "Windsurfing on Mount Baldy",
    "Wonking my conker",
    "Working things out",
    "Working at my own speed",
    "Working late at the office",
    "Working up a foamy lather",
    "Working without Annette",
    "Wrestling the dragon",
    "Wrestling the eel",
    "Wrestling with the bald champ",
    "Wringing out my rope",
    "Some Wrist aerobics",
    "Yanking the crank",
    "Yanking the yo-yo",
    "Yanking my plank",
    "Evicting the testicular squatters",
    "Evicting the testicular squatters",
    "Pooping the pud",
    "Rearranging the deck chairs",
    "Lavishly caressing my own thighs",
    "Spurting into my own hand",
    "Tossing the bagel",
    "Feeding my own dogs",
    "Borrowing Mrs. Frump's bicycle",
    "Riding an automobile",
    "Crushing it to bits",
    "Whipping the beaver",
    "Socking myself in the face with the duster!",
    "Stroking my flabby gut with my belly button lint filter",
    "Warming my bumblebee hive in its nest",
    "Flattening the pillow",
    "Snatching back my hand and going 'I told you so'",
    "Scalding my own back yard",
    "Lacing up the white sneakers",
    "Bouncing the cat",
    "Punching myself in the nose",
    "Lying on the lavender pillows",
    "Thawing the goose on a saran wrap",
    "Whipping the wimp",
    "Cobbal-binging the cussword",
    "Smelling my shirt collar on a rainy day",
    "Nailing my best friend to the shed to rot",
    "Screwing the scullery maid",
    "Blowing up the big red one",
    "Flipping the pork pie",
    "Squirting some mustardy",
    "Sinking fast on this one",
    "Smacking the toaster",
    "Tossing potatoes on high alert",
    "Making the money work",
    "Flexing my ham hock",
    "Busting a gut and going for a walk on Mars",
    "Mucking the meter",
    "Going in and seeing a lady doctor named Miss Jane for the old lady cure",
    "Playing doctor",
    "Making her a man again",
    "Making a meal out of it",
    "Rolling around on a spongecake of cocaine",
    "Catching the canary",
    "Being a chicken wing",
    "Squeezefucking",
    "Cracking a safe",
    "Rubbing one's tuchus",
    "Gulping the goop",
    "Conducting the orchestra",
    "Beef-a-rooneying",
    "Rubbing one's tuchus",
    "Carrying my balsam root to hell",
    "Feeding the chicken",
    "Going out shopping with myself",
    "Frownie, go fishing",
    "Winkie, go dancing",
    "Pretzel face face, make it snuggly snortable facey go go go",
    "Shakin', a shaking' hand from a shake",
    "A jingaling and a singaling from my lips",
    "Whipping and wringing with its little hand",
    "One little finger to pinch one little tinge. YIPPee!",
    "Rubbing the borsalino",
    "Yawning over yon bonfire on my tail",
    "Rising with my right hand my friend. You're at my behest. And in a minute, you can waddle on up the shore, a bit faster too you wannit be",
    "And wah, my dung shall fly as thy name calls me home again?",
    "Blowing myself silly without having the courage to touch myself",
    "Sliding an elbow with one-legged Bob, a maimed-from-behind lover",
    "Sailing on the high seas",
    "Tucking Tinky-Tinky into bed",
    "Squashing my pride",
    "Fending off the flys on the toilet",
    "Feeding the hunk-o-meat, that sweet hunk-o-meat",
    "Feeding the pigeons",
    "Feeding my wacky friend, squirrel-style (tiny but perfectly edible morsel)",
    "Slapping the purple cow's milk bag",
    "Gentle massaging for the ladybug ladybot (but don't let her bite)",
    "Facing my true colors",
    "Fingeling my finicky fizzbuckets",
    "Bending the knee to the great cheese curds of lore for the next one million zillion billion billion years",
    "Thieving eggs from my own backyard free range chicken coop",
    "Chowing down on my own cooking",
    "Gardening with my biker budgie and the one eyed sailor at the pet store",
    "Whack-a-doodle-doo-ing in my palm",
    "Throwing some cream on it",
    "Jailing the worm",
    "Stroking Rosalinda's daffodil bush",
    "Blubbering the baby seal",
    "Beating the bean drum at the county fair",
    "Climbing the tree of happiness",
    "Flogging the log",
    "Killing the one-legged cat with the rooster you got at the bazaar for two dollars",
    "Paddling across the pickle pond with a floating boat. Make sure to save a bucket for catfish and pickles!",
    "Slobbing down raw milk straight from the carton",
    "Just doing some quick math",
    "Dusting off the old furniture",
    "Dismantling the paddy wagon",
    "Watching Fist Freddy and Farkie Fleezie petting their giraffe Alex",
    "Dipping the sausage",
    "Tickling a tittie and pulling off five more to go with it",
    "Dive-bombing without diving or bombing",
    "Rolling a fat one",
    "Pickin' up some hottie in the parking lot, just for sport",
    "Swallowing the one that got away",
    "Making love with your first and last date",
    "Sniping the banana shooter",
    "Pumping the ducky",
    "Going fishing with old Jack Horner",
    "Stuffing the snail",
    "Stroking the snake",
    "Taking the one-armed cruise to paradise",
    "Having a rodeo with the midget",
    "Stirring up the yogurt",
    "Laying the smack on the snicker",
    "Hobbling the mule",
    "Beating the bologna",
    "Stretching the string",
    "Playin' with the one-eyed wonder weasel",
    "Choking the gimp",
    "Rubbing the salami out in the cold night air",
    "Dancing with the wiggler",
    "Shaking that pimp daddy head, dawg... Chill",
    "Munching some meat",
    "Scratching the lottery",
    "Rubber-banding myself in pleasure knots",
    "Painting myself pink like my pet duck, Fanny",
    "Fiddling on the roof",
    "Pulling a rabbit from my magic hat",
    "Pouring gasoline on old Ed's flaming lawn",
    "Acing the interview with myself",
    "Adjusting the minute hand on the old grandfather clock",
    "Practicing my tennis serve with no one around",
    "Hitting the gong. Behold, the Emperor!",
    "Dancing in the rain",
    "Banging your drum solo until the neighbors complain",
    "Hosting a private pity party for one with your little captain as the DJ",
    "Becoming your own porn director and star of the show",
    "Treating Palmela Handerson to a meal at the finest fast food joint in town",
    "Spanking the bishop like you're trying to hit a home run",
    "Buffing the bald-headed golfer until it shines like a diamond",
    "Congratulating yourself for being the world champion of self-love",
    "Taking the law into your own hands and punishing your naughty bits",
    "Touring the international waters of your one-eyed monster like a seasoned sailor",
    "Fulfilling your life's mission of being the best friend your little buddy ever had",
    "calling for reinforcements like a general in a battle against boredom",
    "Achieving a personal best in the one-man Olympic games of self-pleasure",
    "Creating a masterpiece on the ceiling like a modern-day Michelangelo",
    "Jazzing up the flesh flute like a master of improvisation",
    "Taking a ride on the self-love express to orgasm central",
    "Scoring a perfect 10 on the pleasure scale like a judge in a beauty pageant",
    "Riding the knucklehead like a professional bull rider at the rodeo",
    "Gazing upon the sights of the self-love strip like a tourist in Vegas",
    "Crafting your own DIY satisfaction kit like a skilled artisan",
    "Playing a one-man game of five-finger fillet with your sausage while wearing a VR headset",
    "Hosting a solo salsa party for your little captain",
    "Juggling your joystick while watching vintage 70s porn",
    "Taking Palmela Handerson out for a fancy dinner and treating her like a queen",
    "Spanking the bishop like a naughty schoolboy hiding from his mom",
    "Polishing the family jewels like they're the Hope diamond",
    "Shaking hands with the unemployed and congratulating them on their free time",
    "Taking matters into your own hands like a cowboy in the Wild West",
    "Visiting the one-eyed monster like a tourist in a foreign land",
    "Making your little friend happy like it's your mission in life",
    "Calling for backup like a WW2 soldier in the trenches",
    "Beating your own high score like a pro gamer going for a world record",
    "Painting the ceiling like Michelangelo painting the Sistine Chapel",
    "Playing the flesh flute like a virtuoso jazz musician on stage",
    "Taking the self-love train to Pleasureville like a Disney ride for adults",
    "Scoring a hole in one like a golfer aiming for the championship",
    "Mounting the knucklehead like a cowboy riding a bucking bronco",
    "Rubbernecking like a curious tourist in Vegas",
    "Doing some handiwork like a crafty DIY enthusiast",
    "Going solo on stage like a famous singer in a sold-out concert",
    "Taking a trip to Pleasure Island like Pinocchio looking for some fun",
    "Auditioning for the one-man band like a rockstar on a reality show",
    "Painting the town red like a wild party animal on New Year's Eve",
    "Tapping your own maple syrup like a Canadian farmer on a cold winter day",
    "Doing the one-man tango",
    "Having a solo salsa session",
    "Juggling the joystick",
    "Going on a date with Palmela Handerson and a penny in my ass",
    "Spanking the bishop like he's a nasty slut",
    "Polishing the family jewels",
    "Shaking hands with the unemployed",
    "Taking matters into your own hands",
    "Visiting the one-eyed monster",
    "Making your little friend happy",
    "Calling for backup",
    "Beating your own high score",
    "Painting the ceiling",
    "Playing the flesh flute",
    "Taking the self-love train",
    "Scoring a hole in one",
    "Mounting the knucklehead",
    "Rubbernecking on a hot load",
    "Doing some handiwork with my mandiwork",
    "Going solo on stage with my love bazooka",
    "Taking a trip to pleasure island",
    "Auditioning for the one-man band",
    "Painting the town white with bradford pears",
    "Tapping your own maple syrup",
    "Spoiling the catch",
    "Decapitating the insect",
    "Slathering the loaf",
    "Swapping the nappy",
    "Inhaling the foot garment",
    "Obliterating the arthropod",
    "Hydrating the foliage",
    "Plucking the decayed produce",
    "Racing the lethargic gastropod",
    "Exaggerating the froth",
    "Polishing the ol' microphone",
    "Engaging in some high-five diplomacy",
    "Conducting a one-man band",
    "Choking the sherpa guiding you up the mountain",
    "Supercharging the serpent",
    "Introducing the monkey to martial arts",
    "Taking the turkey on a rollercoaster ride",
    "Playing DJ on a human turntable",
    "Enjoying some 'me time' in your personal sanctuary",
    "Performing a one-man orchestra",
    "Unleashing the hog's inner road warrior",
    "Teaching the bishop some wrestling moves",
    "Giving the weasel a crash course in martial arts",
    "Tickling the ol' xylophone",
    "Reenacting Mission: Impossible with the gerbil",
    "Waxing poetic on the board of dreams",
    "Engaging in some self-serenading",
    "Remixing life's soundtrack",
    "Strumming the banjo like a rockstar",
    "Bopping the clown on the nose",
    "Pounding the metaphorical drum of life",
    "Getting acquainted with Sir Fluffington",
    "Venturing into DIY territory",
    "Introducing your salami to a symphony",
    "Going on a journey of self-discovery",
    "Navigating the high seas with the dolphin",
    "Perfecting your aim in the game of life",
    "High-fiving the primate within",
    "Guiding the tiger to the watering hole",
    "Cranking up life's volume to 11",
    "Navigating the meat spaceship through the universe",
    "Serenading the one-eyed snake",
    "High-fiving the hungry caterpillar",
    "Unleashing the mongoose on a wild adventure",
    "Tickling the fancy of your personal genie",
    "Wrestling the Loch Ness monster",
    "Hypnotizing the slithery serpent",
    "Serenading your flesh trumpet",
    "Painting a masterpiece with your solo brush",
    "Tangoing with the tiny dancer",
    "Taming the ham-balaya",
    "Scuba diving with a reluctant eel",
    "Hosting a symposium for one",
    "Challenging the wildling to an arm wrestling match",
    "Engaging in top-secret diplomatic relations",
    "Demonstrating the Kung Fu grip",
    "DJing the soundtrack of your dreams",
    "Hosting a one-hamster dance party",
    "Carving a lonely mountain range",
    "Traversing the desert of self-appreciation",
    "Ticking the tock of your inner clock",
    "Whispering secrets to the dragon",
    "Serenading the cactus in a marathon performance",
    "Juggling the lonely orbs of destiny",
    "Starring in a pilot episode for one",
    "Practicing ninjutsu with the shadow warrior",
    "Frolicking with the fiddly bits",
    "Releasing the Kraken of self-expression",
    "Flying solo on a magic carpet ride",
    "Orchestrating a one-man band of epic proportions",
    "Journeying to the center of the doughnut",
    "Riding the waves of solo synchronicity",
    "Plunging the depths of personal spelunking",
    "Paddling the canoe of cosmic exploration",
    "Jousting with the invisible unicorn",
    "Reigniting the flames of your inner phoenix",
    "Discovering the lost treasure of Atlantis",
    "Stargazing with your private telescope",
    "Mapping the landscape of your dreams",
    "Setting sail on the high seas of self-love",
    "Soaring solo in a spaceship of desire",
    "Rocking the dancefloor with the invisible partner",
    "Tickling the soul strings of your inner muse",
    "Scaling the peaks of personal Everest",
    "Launching a one-rocket mission to the moon",
    "Dancing the tango of self-expression",
    "Taming the wild stallion of independence",
    "Setting the stage for a one-act play",
    "Serenading yourself with sweet symphonies",
    "Dueling with the dragon of duality",
    "Feeding the flames of inner desire",
    "Unlocking the hidden vaults of passion",
    "Charting a course for personal paradise",
    "Navigating the labyrinth of self-discovery",
    "Waltzing with the winds of whimsy",
    "Climbing the heights of hypnotic harmony",
    "Traversing the wilderness of want",
    "Whispering sweet nothings to your egotistical elf",
    "Bathing in the oasis of self-adoration",
    "Skipping stones across the sea of self-satisfaction",
    "Scaling the canyon walls of lonely euphoria",
    "Hiking the trails of tantalizing temptation",
    "Embarking on a voyage of velvety victory",
    "Pouncing on the prey of personal pleasure",
    "Plunging the watery depths of aquatic adventure",
    "Diving headfirst into the pool of personal potential",
    "Fishing for compliments in a sea of self-assurance",
    "Sipping from the chalice of cheeky charm",
    "Rowing through the rapids of rowdy rapture",
    "Soaking in the rays of righteous reflection",
    "Dancing through the desert of delightful delirium",
    "Scaling the staircase of sensual satisfaction",
    "Casting a dreamy spell with the wand of whimsical wizardry",
    "Gliding gracefully through the galaxy of grandeur",
    "Strolling the streets of sultry satisfaction",
    "Skipping along the shores of silken serenity",
    "Parading with pride through personal pomp and circumstance",
    "Jumping for joy in the jubilant jungle",
    "Stuffing the turkey of self-fulfillment",
    "Turning up the heat on the hot plate of hedonism",
    "Reenacting the moon landing with a personal astronaut",
    "Performing a secret handshake with your inner con artist",
    "Conducting a private TED Talk for an audience of one",
    "Operating a solo jackhammer at the construction site of pleasure",
    "Driving the getaway car in a one-man heist",
    "Sweeping the chimney of your inner workshop",
    "Preparing a romantic dinner for the chef within",
    "Breaking out of the prison of self-restraint",
    "Fishing for compliments in the pond of personal gratification",
    "Hosting a one-man baseball game in the stadium of self",
    "Playing a game of one-on-one with your own MVP",
    "Going undercover as a solo private investigator",
    "Serving up a self-appreciation buffet in the kitchen of desire",
    "Leaping across rooftops as your own parkour master",
    "Mastering the game of solitaire in the casino of self-indulgence",
    "Taking a scenic detour on the road to self-satisfaction",
    "Embarking on an archaeological dig of personal passion",
    "Jumpstarting the engine of your heart's hot rod",
    "Scaling the ladder of self-adulation like a high-rise window cleaner",
    "Conducting a top-secret experiment in your personal laboratory",
    "Performing a magic trick for the illusionist within",
    "Gaming the system of self-acceptance with a winning play",
    "Pitching a perfect game to the champion within",
    "Embarking on a solitary spelunking adventure into caverns of carnality",
    "Auditioning for the starring role in your own blockbuster",
    "Dueling with your inner fencing master in a match of self-discovery",
    "Flipping the pancakes of pleasure at the diner of desire",
    "Peeling back the layers of your personal masterpiece",
    "Rowing the gondola of self-adoration through the canals of satisfaction",
    "Breaking into the vault of your hidden treasures",
    "Taking center stage in a one-person performance",
    "Crafting a work of art with the tools of self-exploration",
    "Mowing the lawn of personal satisfaction with a meticulous touch",
    "Exploring the jungle of your heart's desires like a daring adventurer",
    "Navigating the ocean of opportunity like a fearless sea captain",
    "Swinging through the branches of the self-love tree",
    "Scaling the rooftop of your inner skyscraper",
    "Plunging into the deep end of self-adoration",
    "Arranging a rendezvous with your secret agent of self-discovery",
    "Revving the engine of personal achievement in a drag race for one",
    "Summoning the sewer serpent in a one-man excavation",
    "Conducting a symphony of smells in the orchestra pit of pungency",
    "Venturing deep into the gas chamber of gastric distress",
    "Wrestling the swamp monster of perspiration and poots",
    "Unleashing the bog beast from the depths of digestive doom",
    "Waiting in line at the world's worst porta-potty party",
    "Navigating the noxious labyrinth of aromatic annihilation",
    "Accidentally disturbing the ancient burial ground of expired tuna cans",
    "Teaching vile hygiene habits to a putrid posse of pooches",
    "Slogging through a swampy cesspool of discomfort and despair",
    "Juggling the jellyfish of underarm calamity",
    "Captaining the S.S. Stench on a voyage of olfactory offense",
    "Exploring the dank depths of the uncomfortable underbelly",
    "Secretly sharing a medically-inadvisable bean burrito",
    "Sampling the forbidden fruit from the tree of trouser tremors",
    "Discovering the lost city of Atlantis in your own armpits",
    "Cracking open the tomb of the undead babybel cheese wheel",
    "Setting sail on the good ship snot rocket",
    "Dancing a demonic jig on the skull-strewn shores of Stink Island",
    "Marrying the macabre in a one-person ceremony of frenzied flatulence",
    "Provoking the putrid with a dance of festering foot funk",
    "Gently caressing the cold, clammy skin of aquatic atrocity",
    "Releasing the infernal hordes of a thousand cheesy gym socks",
    "Summoning a symphony of sorrow from the depths of digestive despair",
    "Facing off against your own uncomfortable odiferous onslaught",
    "Scaling the Mount Everest of bodily emissions",
    "Navigating the terrain of treacherous toots",
    "Unmastering the art of queasy quivers and queasiness",
    "Skating on thin ice over a lake of sizzling sewage",
    "Digging through the ForbiddenForest of Fungal Fury",
    "Unraveling the yarn ball of gastrointestinal gaffes",
    "Playing barge master on a river of rancid repugnance",
    "Reeking of unspeakable umbrage as you venture through the Valley of Vile",
    "Disturbing the tectonic plates of tantrum-throwing tummies",
    "Poking the sleeping dragon of digestive disaster",
    "Commandeering a one-man submarine through a sea of seething sludge",
    "Fumbling in the dark for the source of the sinister stench",
    "Serenading yourself with the Siren's song of stomach-churning shame",
    "Taking the plunge into the abyss of abhorrent afflictions",
    "Tickling the tarantula of tasteless tactlessness and tumultuous torment",
    "Festerin' in the gumbo turmoil",
    "Unruly swamp trumpet playing",
    "Pungent bayou bellowing",
    "Barn dance crampfesting",
    "Quakin' cornpone convulsive shivering",
    "Howlin' holler shaming horning",
    "Gator-torn britches squirting",
    "Stiflin' smokehouse squirm dangling",
    "Sheep-shorn moonlight shuddering",
    "Weevil-riddled hullabalooing",
    "Wailin' crawfish calamity fixing",
    "from the noodle were Sordid grits discharging ",
    "Clandestine outhouse tangoing",
    "Peculiar possum persuasion didickting",
    "Dixie thunder uproaring",
    "Maddening catfish caressing",
    "Humid hare fandangoing",
    "Tar-touched travesty grenade throwing",
    "Secret sludge serenading",
    "Lonely levee breaks lamenting",
    "Fanboat flustering and fanfaring",
    "Whisperin' willow affliction delivering",
    "Cacklin' critter fiasco slobbering",
    "Cypress swamp surrender muffin",
    "Shriveling kudzu kerfuffle",
    "Currish cottonmouth capering",
    "Abysmal armadillo anguish collapsing in a puddle of oil",
    "Undignified voodoo vista mongoose shriveling",
    "Hot sauce hullaboo inside momma's house",
    "Jambalaya jittering",
    "Muggy mosquito masqueradomg",
    "Tattered tobacco tornado watching",
    "Musty magnolia hotdog dancing",
    "Decayin' delta dilemma diagnosing",
    "Confederate cackle catastrophizing",
    "Torrid town tremor boner",
    "Sultry night-night shenanigan jizz",
    "Sweaty cotillion in sweaty velvetine",
    "Ponderin' premature possum pandemonium",
    "Creole calamity canoodle explosion",
    "Engaging in a solo game of Whack-a-mole with your personal mallet",
    "Rocking the one-eyed microphone like a seasoned performer",
    "Serenading your private parts with a love song of self-indulgence",
    "Conducting an orchestra of self-pleasure like a maestro on a mission",
    "Becoming a one-man puppet show with your personal marionette",
    "Celebrating your body like it's your own private Mardi Gras",
    "Taking a first-class trip to downtown O-town with your personal chauffeur",
    "Practicing your solo home run swing with your favorite bat",
    "Hosting a private hands-on seminar for your personal growth",
    "Playing an intimate game of peek-a-boo with your private eye",
    "Becoming the one-man band of self-satisfaction like a rock legend",
    "Slapping the penguin like it's stolen your lunch money",
    "Taming the wild beast like a skilled animal wrangler",
    "Squeezing the kielbasa like a butcher preparing for a cookout",
    "Tackling your personal Everest like a skilled mountain climber",
    "Surfing the waves of self-love like a pro on the big kahuna",
    "Honing your one-on-one skills like an athlete in training",
    "Conducting a private puppet show for your personal amusement",
    "Hosting the ultimate one-man party like a celebrity on a bender",
    "Throwing a private fiesta for your south of the border amigo",
    "Grappling with the one-eyed wrestler like a professional in the ring",
    "Tossing the salad like a master chef preparing a gourmet meal",
    "Playing a game of one-on-one with your pocket rocket",
    "Tickling the ivories like a pianist in a fancy concert hall",
    "Going on a solo treasure hunt for the pearl of pleasure",
    "Taming the wild stallion like a skilled horse whisperer",
    "Cooking up a storm of self-indulgence like a celebrity chef",
    "Pulling an all-nighter with your one and only study buddy",
    "Hosting a private jam session with your personal drumstick",
    "Guiding your one - eyed wonder worm on an adventure of self - discovery",
    "Dancing with the devil like a possessed exorcist",
    "Celebrating your autonomy like it's Independence Day",
    "Commanding your own personal submarine through uncharted waters",
    "Taking control like a pilot in the cockpit of self-love",
    "Cranking up the volume on your personal boombox of pleasure",
    "Rolling the dice like a high roller in a casino of self-fulfillment",
    "Strumming your heartstrings like a lovesick guitarist",
    "Hitting the high notes like an opera singer in the shower",
    "Taking a one-way trip to ecstasy aboard the pleasure express",
    "Sailing the seas of self-love like a seasoned mariner",
    "Wielding the one-eyed wand like a sorcerer casting a spell",
    "Going on a private date with your undercover lover",
    "Conquering the one-eyed monster like a brave knight",
    "Navigating the labyrinth of self-pleasure like a seasoned explorer",
    "Diving deep into the pool of self-indulgence like a skilled swimmer",
    "Shooting for the stars in a rocket ship of self-love",
    "Driving the pleasure-mobile like a race car driver on a winning streak",
    "Tending to your private garden like a dedicated horticulturist",
    "Scaling the heights of self-satisfaction like a fearless mountaineer",
    "Becoming the one man circus act of personal entertainment",
    "Exploring the caverns of self-satisfaction like a dedicated spelunker",
    "Chasing the elusive one-eyed dragon through the kingdom of pleasure",
    "Taking a solo trip to the top of Mount Ecstasy with your trusty guide",
    "Playing the private bongos of satisfaction like a skilled percussionist",
    "Wrestling the anaconda of pleasure like a fierce jungle explorer",
    "Conducting a one-person orchestra with your pleasure baton",
    "Rowing the boat of self-love down the river of satisfaction",
    "Embarking on a thrilling roller coaster ride of personal delight",
    "Juggling a one-man circus act with your personal equipment",
    "Caressing the velvet rope like a VIP at an exclusive club",
    "Climbing the stairway to heaven on a solo mission of pleasure",
    "Playing peek-a-boo with your undercover agent of satisfaction",
    "Guiding your one-eyed snake through the garden of earthly delights",
    "Steering your personal pleasure boat down the river of lust",
    "Taking a solo spin on the merry-go-round of self-satisfaction",
    "Divining your own pleasure like a skilled water dowser",
    "Polishing the helmet of desire like a devoted soldier",
    "Sailing the ocean of self-love like a fearless pirate captain",
    "Dancing with yourself like a star on a reality show",
    "Unleashing the kraken of pleasure from the depths of your imagination",
    "Launching your personal rocket to the moon of delight",
    "Mastering the art of the one-handed clap with your personal instrument",
    "Firing up the one-man barbecue of satisfaction",
    "Climbing the ladder of self-love like a fearless firefighter",
    "Taking your one-eyed best friend on a trip to the satisfaction station",
    "Embracing the whirlwind of self-pleasure like a storm chaser",
    "Playing solitaire with your personal deck of cards",
    "Turning up the heat on your personal thermostat of desire",
    "Conducting a one-man symphony of ecstatic bliss",
    "Racing down the highway of pleasure on your personal motorcycle",
    "Carving your own path to ecstasy like a skilled mountain climber",
    "Steering your pleasure vessel through uncharted waters",
    "Taming the one-eyed beast like a skilled lion tamer",
    "Embarking on a solo safari through the wilds of desire",
    "Feeding the pleasure monster with your dedicated handiwork",
    "Performing a one-man magic show with your wand of delight",
    "Taking a solo stroll on the beach of self-satisfaction",
    "Navigating the maze of pleasure like a skilled treasure hunter",
    "Riding the waves of self-love like a professional surfer",
    "Daring to tame the wild stallion of desire",
    "Conquering the fortress of personal satisfaction",
    "Swimming the depths of self-pleasure like a deep-sea diver",
    "Scaling the walls of your personal satisfaction castle",
    "Commanding your personal army of pleasure with dedication",
    "Playing your own game of solo chess with your king of desire",
    "Becoming a one-man fireworks display of personal delight",
    "Walking the tightrope of self-pleasure like a skilled acrobat",
    "Operating the levers of satisfaction in your personal control room",
    "Embarking on a thrilling one-man adventure of self-discovery",
    "Juggling the family jewels",
    "Adjusting the antenna",
    "Dancing with the one-eyed sailor",
    "Auditioning the finger puppets",
    "Buffing the banana",
    "Bouncing the bald bishop",
    "Cranking the love pump",
    "Cuffing the carrot",
    "Fondling the flagpole",
    "Giving the one-armed bandit a spin",
    "Greasing the pipe",
    "Hand-to-gland combat",
    "Hitchhiking to heaven",
    "Massaging the mongoose",
    "Patting the penguin",
    "Pumping the python",
    "Riding the self-pleasure express",
    "Rolling the fleshy cigar",
    "Rubbing the magic lamp",
    "Slapping the meat stick",
    "Spanking the monkey",
    "Tending to the trouser snake",
    "Tickling the turkey",
    "Twisting the pepper grinder",
    "Whipping the one-eyed wonder",
    "Wrestling the purple-headed warrior",
    "Yanking the crank",
    "Jazzing the jackrabbit",
    "Pleasing the pocket rocket",
    "Polishing the pearl",
    "Revving the self-engine",
    "Stirring the self-soup",
    "Tackling the tube steak",
    "Tugging the tugboat",
    "Whisking the whisker biscuit",
    "Wooing the womb broom",
    "Working the joystick",
    "Wrestling the eel",
    "Caressing the cream cannon",
    "Charming the trouser snake",
    "Feeding the trouser trout",
    "Flicking the light fantastic",
    "Grooming the groin gopher",
    "Harpooning the salty longshoreman",
    "Polishing the purple helmet",
    "Priming the pump",
    "Roughing up the suspect",
    "Tossing the one-eyed trouser trout",
    "Tugging the slug",
    "Waxing the dolphin",
    "Whacking the weasel",
    "Winding up the pocket watch",
    "Working the one-eyed wonder worm",
    "Plunging into the whirlpool of wild whimsy",
    "Unlocking the hidden vault of your inner gonzo",
    "Riding the wave of your own twisted imagination",
    "Taming the beast of bizarre within",
    "Taking a trip down the rabbit hole of your psyche",
    "Embarking on a mind-bending journey through the realms of strangeness",
    "Wrestling the cosmic alligator of unconventional thought",
    "Launching the rocket of your own unconventional wisdom",
    "Diving headfirst into the abyss of your personal oddities",
    "Soaring through the skies of surrealism on the wings of self-expression",
    "Becoming the ringmaster of your own circus of chaos",
    "Spinning the roulette wheel of your mind's peculiarities",
    "Conducting a symphony of eccentricities in your inner orchestra",
    "Breaking the chains of conformity with a howl of creative rebellion",
    "Unleashing the whirlwind of your own peculiar passions",
    "Exploring the depths of your own twisted sense of humor",
    "Mingling with the peculiar characters of your personal menagerie",
    "Navigating the landscape of your own uncharted eccentricity",
    "Traversing the treacherous terrain of your own peculiarities",
    "Climbing the mountain of madness in search of self-enlightenment",
    "Daring to defy the ordinary in pursuit of the extraordinary",
    "Poking the bear of convention with a stick of wild abandon",
    "Skipping merrily through the minefield of your own peculiar tendencies",
    "Dancing with the devil in the pale moonlight of your own strange inclinations",
    "Galloping through the wilderness of your own unbridled imagination",
    "Hitchhiking through the galaxy of your own idiosyncrasies",
    "Unmasking the hidden secrets of your own inner freak show",
    "Strolling through the hallways of your own haunted mansion",
    "Raising the flag of your own freakishness in a salute to individuality",
    "Tiptoeing through the tulips of your own twisted daydreams",
    "Swinging from the chandeliers of your own personal carnival",
    "Scaling the walls of your own fortress of weirdness",
    "Tunneling through the mazes of your own peculiar mind",
    "Firing up the engine of your own unique worldview",
    "Strutting down the runway of your own distinctive style",
    "Tasting the forbidden fruit of your inner oddball",
    "Feasting on the buffet of your own bizarre proclivities",
    "Juggling the flaming torches of your own peculiar predilections",
    "Leaping across the chasm of your own unorthodox ideas",
    "Frolicking through the fields of your own fantastic fancies",
    "Serenading your own inner freak with a song of self-embrace",
    "Stepping into the spotlight of your own self-created stage",
    "Dancing to the beat of your own drum in the parade of peculiarity",
    "Delving into the depths of the peculiar pantry for a self-satisfying snack",
    "Orchestrating a one-man symphony of strange sensations",
    "Releasing the confetti cannon of self-pleasing curiosities",
    "Playing a game of solitaire with the deck of deranged desires",
    "Tickling the tentacles of the mischievous mind squid",
    "Waltzing through the wonderland of warped wants and whims",
    "Partaking in a one-person puppet show of peculiar passions",
    "Summoning the succulent serpent of self-serving satisfaction",
    "Bathing in the bubbling cauldron of kooky cravings",
    "Piloting the peculiar plane of personal predilections",
    "Feasting upon the buffet of bizarre and bewildering banquets",
    "Bending the spoon of sanity with the power of your personal peculiarities",
    "Scaling the tower of twisted temptation in search of self-gratification",
    "Unlocking the Pandora's box of perplexing peccadilloes",
    "Reveling in the carnival of carnal curiosities and capricious capers",
    "Juggling the jigsaw pieces of your own jumbled joys",
    "Tending to the twisted tree of tantalizing temptations",
    "Conducting a seance to summon the spirits of self-serving satisfaction",
    "Navigating the twisted labyrinth of licentious longings and ludicrous lusts",
    "Unraveling the tangled web of your own bizarre and beguiling bedroom behaviors",
    "Marching to the beat of a different drum in the parade of peculiar predilections",
    "Galloping through the garden of grotesque and gleeful gratification",
    "Wrangling the wild stallion of strange and stimulating sensations",
    "Swimming in the sea of salacious and surreal self-satisfying scenarios",
    "Frolicking through the forest of freakish fantasies and feral fancies",
    "Embarking on a one-man expedition to explore the exotic islands of eccentric erotica",
    "Riding the bucking bronco of bizarre and boisterous bedroom behaviors",
    "Diving into the pool of perplexing pleasure and perplexing passions",
    "Ascending the mountain of madness to reach the summit of self-service",
    "Taming the untamed beast of bewildering bedroom buffoonery",
    "Plunging into the ocean of outlandish and offbeat orgasms",
    "Spelunking in the caves of curious carnal capers and caprices",
    "Navigating the river of raunchy and ribald romantic rendezvous",
    "Wandering through the wilderness of wanton and wicked whims",
    "Exploring the enchanted forest of eerie and eccentric eroticism",
    "Dancing with the demons of deviant and demented desires",
    "Constructing a castle of curious and quirky carnal cravings",
    "Sailing the stormy seas of salacious and scandalous scenarios",
    "Playing the pied piper of peculiar and perplexing pillow play",
    "Scaling the treacherous cliffs of twisted and titillating temptations",
    "Soaring through the skies of scandalous and surreal sexual shenanigans",
    "Excavating the crypt of kinky and curious carnal caprices",
    "Paddling through the swamp of salacious and scandalous sensations",
    "Embarking on a one-man odyssey to discover the uncharted territories of titillating temptations",
    "Plumbing the depths of the abyss of aberrant and absurd amorous adventures",
    "Galloping on the winds of wild and wacky whims and witticisms",
    "Sauntering through the hall of mirrors reflecting your risqué and riotous reveries",
    "Adventuring through the amusement park of astounding and audacious appetites",
    "Journeying into the heart of darkness to uncover the secrets of sinful and strange seductions",
    "Voyaging through the vortex of voluptuous and villainous vices",
    "Delving into the dungeon of debauched and devilish dalliances",
    "Solving the mysterious riddles of raunchy and rambunctious rollicking",
    "Embarking on a surreal safari to hunt the beasts of bewitching and bizarre bedroom behaviors",
    "Chasing the elusive phantom of cryptic and curious carnal capers",
    "Unveiling the hidden treasures of tantalizing and titillating trysts",
    "Discovering the lost city of lascivious and loony liaisons",
    "Unearthing the ancient secrets of aberrant and abnormal amore",
    "Deciphering the enigmatic code of eccentric and erotic enigmas",
    "Venturing into the shadowy realm of sinful and scandalous self-indulgence",
    "Traversing the treacherous terrain of torrid and twisted titillation",
    "Wading through the murky waters of murky and mischievous meanderings",
    "Conducting a one-handed symphony of self-indulgence",
    "Commandeering the skin canoe",
    "Churning the butter of bodily bliss",
    "Consulting with the council of five fingers",
    "Cranking the love pump",
    "Dancing with the one-eyed diplomat",
    "Delighting in a session of hand-to-gland combat",
    "Deploying the troops of self-gratification",
    "Discovering the cave of carnal knowledge",
    "Engaging in some undercover handiwork",
    "Exercising the love muscle",
    "Feeding the geese of inner pleasure",
    "Fondling the forbidden fruit",
    "Frolicking in a solo soiree of satisfaction",
    "Fulfilling the prophecy of the five-fingered prophet",
    "Gathering the pearls of personal passion",
    "Greasing the wheels of whimsy",
    "Honing the horn of hedonistic happiness",
    "Indulging in a session of self-love",
    "Inventing the wheel of wanton wonder",
    "Launching the rocket of rapturous release",
    "Liberating the love tornado",
    "Lovingly tending to the garden of sensual satisfaction",
    "Manipulating the marionette of masculine mystique",
    "Meditating on the mysteries of one's own flesh",
    "Minding the manly manacle",
    "Nurturing the naughty nub of nirvana",
    "Painting the ceiling with the passion palette",
    "Pampering the palm pony",
    "Partaking in a steamy session of handball",
    "Piloting the pleasure cruise",
    "Playing solitaire on the skin flute",
    "Polishing the pearl of personal pleasure",
    "Pondering the enigma of one's own essence",
    "Practicing the art of self-enchantment",
    "Preparing the altar of aphrodisiac adoration",
    "Riding the waves of self-discovery",
    "Sailing the self-service seas",
    "Savoring the sweet fruits of self-embrace",
    "Serenading the serpent of sensuality",
    "Shaking hands with the unemployed",
    "Shedding the shackles of self-denial",
    "Slippery-sloping to solitary satisfaction",
    "Solving the riddle of one's own ecstasy",
    "Spelunking the caverns of carnal delight",
    "Spinning the wheel of wantonness",
    "Stroking the stallion of self-adoration",
    "Summoning the genie of genital gusto",
    "Taming the wild beast of bodily bewilderment",
    "Teasing the tiger of tempestuous titillation",
    "Toying with the totem of turgid temptation",
    "Treading the path of private passion",
    "Tuning the strings of sensual serenades",
    "Unleashing the dragon of desire",
    "Venturing into the valley of voluptuous veneration",
    "Waltzing with the widow's husband",
    "Wandering the uncharted territories of titillation",
    "Whipping up a whirlwind of wanton whimsy",
    "Winning the one-man marathon of madness",
    "Wrestling with the unspoken urges",
    "Yodeling in the canyon of carnal concupiscence",
    "Zipping through the pleasure zone of zealous zest",
    "Zooming along the zesty zipline of zing",
    "Channeling the chakra of carnal cravings",
    "Dallying with the dervish of dalliance",
    "Entwining the essence of erotic enchantment",
    "Galloping through the grove of groovy gratification",
    "Harnessing the hurricane of hedonistic hunger",
    "Illuminating the inner sanctum of indulgent impulses",
    "Juggling the jewels of jubilant joy",
    "Kindling the fire of carnal knowledge",
    "Liberating the leviathan of lustful longings",
    "Manipulating the mirthful marauder of merriment",
    "Nourishing the naughty navigator of nirvana",
    "Orchestrating an opus of orgasmic oscillations",
    "Paddling the passionate porpoise of pleasure",
    "Quenching the quixotic quest of quivering quarks",
    "Revving the rambunctious rascal of rapturous release",
    "Seducing the sultry serpent of scintillating satisfaction",
    "Tickling the titillating titan of tantalizing temptation",
    "Unraveling the unfathomable universe of unbridled urges",
    "Vanquishing the voracious vixen of visceral veneration",
    "Wrestling the wily warlock of wanton whimsy",
    "X-raying the xanadu of x-rated xantheins",
    "Yanking the yearning yachtsman of youthful yonder",
    "Zapping the zealous zephyr of zesty zeal",
    "Awakening the arcane acrobat of amorous adventures",
    "Beating the bewildering banshee of boisterous bacchanalia",
    "Chasing the chimeric chimera of carnal choreography",
    "Delighting in the dance of dextrous dalliance",
    "Exalting the exuberant exhibitionist of existential ecstasy",
    "Fostering the frenetic firebrand of feverish frolic",
    "Grooming the gregarious gryphon of gratifying gallantry",
    "Heralding the hedonistic harbinger of heartfelt happiness",
    "Igniting the irreverent imp of impassioned indulgence",
    "Jostling the jubilant juggernaut of joyous jocularity",
    "Kindling the kaleidoscopic knight of kinky kismet",
    "Lyrical liaison with the lascivious lark of luxurious leisure",
    "Mingling with the mischievous muse of masterful merrymaking",
    "Nurturing the nubile nymph of nectarous nascence",
    "Oscillating with the opulent oracle of orgasmic oracles",
    "Partaking in the primal parade of pulsating passions",
    "Questing for the quivering quasar of quintessential quiescence",
    "Riding the rollicking rollercoaster of rousing revelry",
    "Savoring the salacious symphony of syncopated sensations",
    "Tempting the tumultuous tango of titillating trysts",
    "Unearthing the uncharted utopia of unquenchable urges",
    "Venerating the vivacious vanguard of voluptuous ventures",
    "Wooing the wondrous whirlwind of whirling wantonness",
    "Xylophonically xeroxing the xenium of xiphoid xerosis",
    "Yearning for the yonder of yesteryear's youthful yore",
    "Zestfully zipping through the ziggurat of zirconium zaniness",
    "Abracadabra-ing the amiable acropolis of amorous attraction",
    "Bewitching the beguiling behemoth of bacchanalian bliss",
    "Conjuring the capricious cerberus of corporeal communion",
    "Delighting in the dervish of dappled dalliance",
    "Entwining the ethereal eel of edenic ecstasy",
    "Frolicking with the frisky firefly of flirtatious fervor",
    "Gyrating with the gleeful gargoyle of giddy gratification",
    "Hobnobbing with the hallowed harpy of hedonistic harmony",
    "Invoking the insatiable incubus of inimitable indulgence",
    "Juggling the jubilant jackal of jocund jollity",
    "Kaleidoscopically kissing the kismet of kindred kinks",
    "Liltingly luxuriating with the luscious lyrebird of lust",
    "Merrily mingling with the moirai of mischievous mirth",
    "Nibbling at the nectar of nubile naiads and nymphs",
    "Obliterating the obtuse obelisk of obfuscated onanism",
    "Prancing with the prurient pixie of provocative pleasure",
    "Quixotically quantifying the quarks of quivering quagmires",
    "Romping with the rambunctious roc of rapturous rhapsody",
    "Serenading the sylphs of sultry satisfaction and seduction",
    "Tantalizing the titans of tempestuous titillation",
    "Unfurling the unfathomable ursa of unyielding ululation",
    "Voyaging with the vivacious valkyries of voluptuous vanity",
    "Waltzing with the wistful wraiths of winsome wanderlust",
    "Xiphoidally x-raying the xenografts of xeric xylography",
    "Yelling yippees with the yeomanry of Yggdrasil's yonders",
    "Zinging zodiacal zigs with the zorro of zany zloty",
    "Aerial acrobatics with the alluring angels of amour",
    "Bestowing blessings on the bodacious bodhisattvas of bliss",
    "Cherishing chimeras of cherubic charms and chancery",
    "Dallying with the demimonde of delightful dalliance",
    "Entwining the effulgent eidolons of Elysian enchantment",
    "Frolicking with the fabulous fates of fervid fantasy",
    "Gamboling with the gregarious gods of gushy gladness",
    "Harmonizing with the heavenly harbingers of hallowed happiness",
    "Imbibing the idyllic ichor of ineffable indulgence",
    "Juggling the jovial juggernauts of jocose joy",
    "Kissing the kenspeckle kelpies of kaleidoscopic kink",
    "Luxuriating with the lustrous leviathans of lewd longing",
    "Musing with the mystic muses of mesmeric merriment",
    "Nestling with the nymphal naiades of nacreous nuzzling",
    "Obliterating the opalescent opsimaths of orphic oscillation",
    "Prancing with the piquant phantasms of pellucid pleasure",
    "Quivering with the quixotic quintessence of querulous qanats",
    "Reveling with the resplendent revenants of rapture",
    "Sashaying with the spectral sprites of spirited seduction",
    "Tapping the transcendent trove of titillating treasure",
    "Unveiling the unfathomable ukiyo of untrammeled unity",
    "Voyaging with the voluptuous vixens of vibrant vim",
    "Wandering with the winsome wights of wanton wiles",
    "Xenophobically xeroxing the xanthic xerophagy of xenotime",
    "Yodeling with the yeasty yahoos of yearning yachtsmanship",
    "Zephyrizing zetetic ziggurats with the zulu of zymotic zealotry",
    "Amalgamating the arcane artifices of aphrodisiac ardor",
    "Billeting the benthic bacchantes of bawdy banter",
    "Calibrating the caliginous caliphate of carnal caprice",
    "Dismantling the dionysian diorama of delirious delight",
    "Embracing the ethereal effervescence of erotic ebullience",
    "Fathoming the fathomless fata morgana of febrile felicity",
    "Gallivanting with the galactic gargantua of grandiose gratification",
    "Churning the butter with Sir Whack-a-Lot",
    "Summoning the trouser genie",
    "Taming the one-eyed trouser snake",
    "Basting the sausage in private",
    "Auditioning the meat puppet",
    "Banging the banger with a spot of DIY",
    "Tickling the tallywhacker",
    "Dancing with the disco stick",
    "Engaging in a spot of knob-jockeying",
    "Firing the flesh musket",
    "Grasping the gherkin of passion",
    "Honing the horn of plenty",
    "Jousting with the one-eyed knight",
    "Launching the custard rocket",
    "Polishing the ol' pork sword",
    "Riding the five-fingered knuckle express",
    "Shaking hands with the governor",
    "Tossing the todger",
    "Unleashing the kraken of lust",
    "Venturing on a wanktastic voyage",
    "Whipping the willy with fervor",
    "Exploring the cave of the two-headed dragon",
    "Captaining the tugboat to Pleasure Island",
    "Greasing the ferret in solace",
    "Feeding the one-eyed trouser trout",
    "Dueling with the pink lightsaber",
    "Waking up the sleepy bishop",
    "Sending the hand shuttle to the moon",
    "Playing the skin trumpet solo",
    "Bouncing the banger in a one-man band",
    "Consulting with Dr. Wankenstein",
    "Fetching the trouser mouse some cheese",
    "Hammering the one-eyed nail",
    "Inflating the tube of passion",
    "Jerking the joy stick",
    "Kneading the dough of desire",
    "Lifting the luggage in the airport of ecstasy",
    "Muffling the man horn",
    "Noodling the noodle",
    "Oiling the oyster in seclusion",
    "Paddling the pink canoe of manhood",
    "Quenching the quivering quill",
    "Rolling the love log",
    "Sawing the sausage of solitude",
    "Tickling the trout of temptation",
    "Ushering the unicorn into the valley of relief",
    "Vexing the velvet viper",
    "Whittling the woodpecker of want",
    "Exercising the eel of excitement",
    "Yanking the yodeling Yeti",
    "Zapping the zebra of zeal",
    "Adjusting the antenna of ardor",
    "Bouncing the bollocks of bliss",
    "Climbing the column of carnality",
    "Doodling the dingle of delight",
    "Erupting the volcano of virility",
    "Flicking the fleshy flute",
    "Galloping with the randy stallion",
    "Hitching a ride on the hand express",
    "Igniting the rocket of rapture",
    "Juggling the jewels of jubilation",
    "Kissing the cobra of kink",
    "Launching the love torpedo",
    "Massaging the mutton of merriment",
    "Nibbling the nub of naughtiness",
    "Ogling the ogre of orgasm",
    "Poking the porcupine of pleasure",
    "Quashing the quiver of quenching",
    "Riding the rambunctious rattlesnake",
    "Savoring the sausage of satisfaction",
    "Tweaking the twig of titillation",
    "Unveiling the unicorn of unbridled joy",
    "Vibrating the viper of victory",
    "Wrestling the randy rhinoceros",
    "Yodeling with the yammering yak",
    "Zipping the zipper of zest",
    "Navigating the meat canoe",
    "Piloting the pork airplane",
    "Quivering the quagmire of quench",
    "Reeling in the randy rascal",
    "Slapping the salacious serpent",
    "Tugging the tumultuous tiger",
    "Unwrapping the eager eel",
    "Voyaging the veiny vessel",
    "Waxing the wiggly walrus",
    "X-raying the x-rated xylophone",
    "Yoking the yearning yak",
    "Zigzagging the zesty zucchini",
    "Arm wrestling the anaconda",
    "Befriending the bawdy badger",
    "Caressing the captivating cactus",
    "Dipping the daring dingo",
    "Easing the eager elephant",
    "Fondling the frisky fox",
    "Gripping the gyrating giraffe",
    "Hugging the horny hedgehog",
    "Inspecting the insatiable iguana",
    "Jostling the jocular jaguar",
    "Kindling the kinky kangaroo",
    "Luring the lascivious lobster",
    "Mauling the mischievous mongoose",
    "Nursing the naughty narwhal",
    "Oscillating the orgasmic ostrich",
    "Prancing the passionate panda",
    "Quaking the quirky quail",
    "Routing the rambunctious raccoon",
    "Squeezing the salivating snake",
    "Taming the titillating tapeworm",
    "Uncorking the unyielding urchin",
    "Vexing the voracious vulture",
    "Waltzing the wanton weasel",
    "X-ing the xenophobic xerus",
    "Yawning at the yielding yak",
    "Zooming the zany zebra",
    "Apprehending the ardent armadillo",
    "Bothering the bumptious boar",
    "Coddling the coquettish coyote",
    "Dallying with the dashing dachshund",
    "Enticing the erotic egret",
    "Frolicking with the frisky ferret",
    "Gliding with the giddy goat",
    "Handling the hankering hippo",
    "Intertwining with the insistent iguana",
    "Jiggling the jaunty jackal",
    "Kissing the keen koala",
    "Loving the lascivious lemur",
    "Mingling with the mischievous monkey",
    "Nuzzling the nifty newt",
    "Ogling the obstinate ocelot",
    "Playing with the piquant porcupine",
    "Quelling the quizzical quokka",
    "Ravishing the ravenous rabbit",
    "Seducing the sultry squirrel",
    "Tickling the tantalizing tortoise",
    "Unscrewing the uppity unicorn",
    "Vexing the vivacious vixen",
    "Wooing the wicked wombat",
    "Xeroxing the xenomorphic xoloitzcuintli",
    "Yearning for the yielding yabby",
    "Zesting the zealous zorse",
    "Aggravating the amorous alligator",
    "Basting the brazen bat",
    "Cajoling the carnal camel",
    "Disturbing the desirous donkey",
    "Enrapturing the enamored eagle",
    "Fumbling the feisty falcon",
    "Groping the gregarious gopher",
    "Hassling the heated hyena",
    "Indulging the insistent impala",
    "Juggling the jaunty jay",
    "Kneading the knotty kinkajou",
    "Lulling the lewd lynx",
    "Manhandling the maddening marmot",
    "Nestling the naughty numbat",
    "Overwhelming the oozing octopus",
    "Pampering the passionate platypus",
    "Quivering the quaking quetzal",
    "Romancing the ravenous rooster",
    "Savoring the seductive snail",
    "Teasing the tempestuous terrier",
    "Unhinging the unquenchable urchin",
    "Vibrating the vivacious vole",
    "Wheedling the wanton walleye",
    "X-citing the x-rated xiphias",
    "Yelping at the yearning yucca",
    "Zapping the zealous zonkey",
    "Galloping the frisky stallion",
    "Beating the bedroom drum",
    "Charming the one-eyed snake",
    "Cheering on the easy rider",
    "Doing the knuckle shuffle",
    "Exercising the monkey",
    "Feeding the trouser snake",
    "Grasping the manly baton",
    "Hammering the nail of passion",
    "Initiating a solo symphony",
    "Juggling the meatballs",
    "Kicking the bedroom football",
    "Lubricating the love piston",
    "Massaging the ego",
    "Negotiating with the purple-headed ambassador",
    "Oiling the machinery",
    "Preparing the mayonnaise cannon",
    "Quivering the quaking quail",
    "Rolling the rock of ages",
    "Stroking the furry wall",
    "Taming the shrew",
    "Unleashing the snake charmer",
    "Venturing into the cave of wonders",
    "Wrestling with the tentacle monster",
    "X-ing the love crossroads",
    "Yanking the chain of desire",
    "Zipping the love zipper",
    "Adjusting the bedroom antenna",
    "Buffing the banana",
    "Caressing the velvet dragon",
    "Declaring a thumb war",
    "Engaging the love engine",
    "Feeling the force of the Jedi",
    "Going on a date with Rosie Palm",
    "Having a word with the master debater",
    "Inviting the five-fingered disco dancer",
    "Jostling the jumbo shrimp",
    "Knocking on the devil's door",
    "Lifting the love weight",
    "Maneuvering the meat missile",
    "Noodling the noodle",
    "Organizing the orgy of one",
    "Playing pocket pool",
    "Quenching the thirst of the love fountain",
    "Riding the rocket solo",
    "Shaking the snake charmer",
    "Teasing the trouser trout",
    "Unraveling the tapestry of temptation",
    "Visiting the cave of the golden dragon",
    "Wooing the one-eyed wonder weasel",
    "X-pressing the love button",
    "Yodeling with the lonely lumberjack",
    "Zoning in on the zone of desire",
    "Attending the self-pleasure symposium",
    "Blowing the love horn",
    "Checking the undercarriage",
    "Driving the one-armed bandit",
    "Exorcising the lustful demon",
    "Feasting on the forbidden fruit",
    "Grabbing the love grenade",
    "Hunting the feral trouser ferret",
    "Inflating the inner tube of ecstasy",
    "Jiving with the joy stick",
    "Kneading the dough of desire",
    "Launching the hand rocket",
    "Milking the midnight moo cow",
    "Nibbling the naughty nugget",
    "Owning the oyster of pleasure",
    "Polishing the love helmet",
    "Quieting the quivering quokka",
    "Releasing the hounds of desire",
    "Sparring with the one-eyed champion",
    "Tickling the tiger",
    "Unzipping the passion pouch",
    "Voyaging the veiny voyage",
    "Waking the morning wood",
    "X-changing secrets with the x-rated xyster",
    "Yearning with the young yodler",
    "Zooming the zesty ziggurat",
    "Unlocking the treasure chest of self-indulgence",
    "Riding the wave of personal pleasure",
    "Taking a solo flight in the cockpit of satisfaction",
    "Revving the engine of self-gratification",
    "Conducting a one-man orchestra of ecstasy",
    "Mining for gold in the cave of carnal delight",
    "Feeding the trouser beast of desire",
    "Launching a solo mission to the moon of euphoria",
    "Whistling dixie with the flesh flute",
    "Taming the wild beast in the jungle of lust",
    "Exploring the uncharted territory of self-love",
    "Playing a game of one-on-one with the pleasure pro",
    "Taking the reins of passion's wild stallion",
    "Bouncing on the trampoline of temptation",
    "Navigating the rapids of rapture",
    "Wrestling the wildcat of wantonness",
    "Igniting the rocket of rapture",
    "Journeying through the valley of self-discovery",
    "Scaling the mountain of masculine desire",
    "Painting a masterpiece on the canvas of carnality",
    "Tugging the rope of rhapsody",
    "Cooking up a storm in the kitchen of kink",
    "Finding the pot of gold at the end of the pleasure rainbow",
    "Chasing the tantalizing tiger of temptation",
    "Conquering the mountain of manly urges",
    "Taking a daring dip in the pool of personal passion",
    "Building a sandcastle of satisfaction on the beach of bliss",
    "Embarking on a solo expedition to the peak of pleasure",
    "Feeling the heat in the kitchen of carnal cravings",
    "Unleashing the beast of bodily indulgence",
    "Summoning the spirit of sensual satisfaction",
    "Mastering the maze of manly desire",
    "Playing with the joystick of jubilation",
    "Climbing the ladder of lascivious longing",
    "Firing up the furnace of fervor",
    "Diving into the depths of decadent delight",
    "Wandering through the wilderness of wanton whimsy",
    "Unraveling the mysteries of masculine mirth",
    "Sailing the sea of sensual satisfaction",
    "Tilling the soil of titillation",
    "Honing the blade of hedonistic happiness",
    "Tapping into the well of wickedly wonderful wishes",
    "Venturing forth into the land of lustful longings",
    "Harvesting the fruits of forbidden fantasies",
    "Unlocking the door to the den of delight",
    "Exploring the outer reaches of rapturous reverie",
    "Paddling down the river of ribald recreation",
    "Trekking through the tantalizing territory of temptation",
    "Feasting at the banquet of bawdy bacchanalia",
    "Navigating the nebula of naughty notions",
    "Conquering the castle of carnal conquest",
    "Plumbing the depths of personal pleasure",
    "Discovering the delights of the delectable domain",
    "Dancing the dance of devilish diversion",
    "Embarking on a solo journey to the summit of satisfaction",
    "Polishing the forbidden scepter",
    "Riding the wave of solitary sin",
    "Taming the beast of bedroom debauchery",
    "Unleashing the kraken of kink",
    "Venturing into the valley of vulgar vices",
    "Wrestling with the filthy phantom",
    "Exorcising the demon of dirty deeds",
    "Yanking the chain of shameless shenanigans",
    "Zipping along the zipline of zestful zeal",
    "Blasting off on a rocket of raunchy revelry",
    "Caressing the cobra of carnal cravings",
    "Divulging secrets to the deviant diplomat",
    "Entertaining the emperor of erotic escapades",
    "Feeding the monster of midnight mischief",
    "Grinding the gears of gratuitous gratification",
    "Hijacking the highway of hedonistic hijinks",
    "Igniting the inferno of indecent indulgences",
    "Juggling the jewels of jaw-dropping joyrides",
    "Kneading the knots of kinky knavery",
    "Launching the lustful locomotive",
    "Mining for gold in the gutter of grotesque gaiety",
    "Navigating the naughty nebula",
    "Operating the obscene orchestra",
    "Plundering the palace of perverse pleasure",
    "Quenching the thirst of questionable quests",
    "Ravaging the realms of raucous rapture",
    "Saddling the steed of salacious satisfaction",
    "Tickling the tentacles of tawdry temptation",
    "Unraveling the web of unbridled urges",
    "Venturing into the vortex of villainous vixens",
    "Waltzing with the wicked warlock",
    "X-raying the x-rated xanadu",
    "Yielding to the yowling yeti of yearning",
    "Zooming through the zany zone of zealous zest",
    "Plunging into the well of self-discovery",
    "Taming the salacious serpent",
    "Unlocking the passion padlock",
    "Whipping the whirlwind of desire",
    "X-raying the x-factor of ecstasy",
    "Yodeling in the canyon of carnal pleasure",
    "Zigzagging through the zone of zealous exploration",
    "Aiming the arrow of arousal",
    "Blowing the horn of hedonism",
    "Climbing the tower of temptation",
    "Dancing with the devilish dervish",
    "Escaping to the island of indulgence",
    "Flipping the switch of satisfaction",
    "Gliding through the garden of guilty pleasures",
    "Harnessing the hurricane of heat",
    "Illuminating the lantern of lust",
    "Jumpstarting the joyride of jubilation",
    "Kindling the flame of kinkiness",
    "Lassoing the lusting stallion of loneliness",
    "Meandering through the maze of masculine mystique",
    "Nurturing the naughty nymph of night-time naughtiness",
    "Opening the oyster of obsession",
    "Plucking the strings of self-pleasure",
    "Questing for the quivering quasar of quietude",
    "Riding the rollercoaster of racy recreation",
    "Summoning the sensual specter of seclusion",
    "Tickling the tiger of tantalizing touch",
    "Unleashing the unicorn of unbridled urges",
    "Vaulting over the velvet rope of vice",
    "Wandering the wicked ways of wild wantonness",
    "Xeroxing the xoxo of x-rated exploits",
    "Yanking the chain of yearning",
    "Zapping the zipper of zealous zaniness",
    "Appreciating the art of alone time",
    "Bouncing on the bungee of bodily bliss",
    "Chasing the comet of carnal contentment",
    "Dipping into the pool of personal passion",
    "Exploring the enchanted forest of ecstasy",
    "Fishing for the frenzied fun of forbidden fruit",
    "Gracing the stage of guilty gratification",
    "Hitching a ride on the highway of heated happiness",
    "Igniting the spark of insatiable itch",
    "Jousting with the jester of joy",
    "Kissing the sky of kismet-driven kink",
    "Launching the rocket of lascivious luxury",
    "Meditating on the mantra of me-time",
    "Navigating the nexus of nighttime naughtiness",
    "Orchestrating the opusof orgasmic odes",
    "Playing the piccolo of passionate peaks",
    "Quivering in the quagmire of quirky quests",
    "Riddling the riddle of raucous rapture",
    "Sailing the sea of solitary satisfaction",
    "Tickling the ivories of titillating triumphs",
    "Unwrapping the gift of guilty pleasure",
    "Voyaging the vessel of velvet vices",
    "Wrestling the warriors of wild wantonness",
    "Xylophoning the xanadu of x-rated xcitement",
    "Yearning for the yoke of youthful yield",
    "Zooming the zenith of zealous zingers",
    "Ascending the apex of aphrodisiacal adventure",
    "Boomeranging the boundless bliss of bold bravado",
    "Carving the canyon of carnal crescendo",
    "Doubling the daring deeds of delightful dalliance",
    "Eclipsing the eternal ecstasy of elated euphoria",
    "Flicking the flame of fevered fantasy",
    "Galloping the gusty gales of grandiose gratification",
    "Hovering the hallowed halls of heated heaven",
    "Imbibing the intoxicating inebriation of impassioned inspiration",
    "Jumping the jagged jaws of jubilant jocularity",
    "Kowtowing the kaleidoscope of kinetic kismet",
    "Levitating the lofty layers of libidinous longing",
    "Manipulating the malleable mirth of masterful merriment",
    "Nomadizing the netherworld of nocturnal nirvana",
    "Oscillating the obelisk of orgasmic overture",
    "Pulsating the powerful pulse of primal pursuit",
    "Quaking the quixotic quest of quenched quenchlessness",
    "Reveling the rambunctious rapture of riotous rhapsody",
    "Swimming the swirling sea of sublime seduction",
    "Tangling the taut threads of torrid temptation",
    "Unfurling the undulating waves of unspoken urges",
    "Vibrating the vaunted vortex of voracious ventures",
    "Waxing the waning whirlwind of wanton wonder",
    "X-ing the xeric xyst of xenial xanthippe",
    "Yielding the yonder yore of yesteryear's yearning",
    "Zesting the zephyr of zesty zeal",
    "Plunging into the filthy abyss of self-pleasure",
    "Riding the raunchy roller coaster of sin",
    "Taming the insatiable demon of desire",
    "Unleashing the beast from the swamp of lust",
    "Venturing into the cesspool of salacious satisfaction",
    "Wrestling with the filthy serpent of indulgence",
    "Yanking the chain of depraved debauchery",
    "Zipping through the vulgar vortex of vice",
    "Adjusting the antenna of egregious ecstasy",
    "Blowing the horn of hedonistic horrors",
    "Churning the butter of carnal corruption",
    "Defiling the altar of obscene offerings",
    "Escaping into the underworld of ungodly gratification",
    "Feeding the monstrous cravings of the flesh",
    "Grinding the gears of grotesque glee",
    "Harvesting the depraved desires of the id",
    "Invoking the white stained spirits of scandalous acts",
    "Juggling the jewels of jaw-dropping perversion",
    "Kneading the twisted knots of kink",
    "Lashing the lewd leviathan of longing",
    "Milking the udders of unrighteous urges",
    "Navigating the sewer of sinful sensations",
    "Opening the gates of the forbidden city",
    "Pandering to the perversions of the psyche",
    "Quenching the thirst of a deviant appetite",
    "Ravaging the recesses of ribald rapture",
    "Scouring the grimy gutters of guilty pleasure",
    "Tickling the tentacles of taboo temptation",
    "Unleashing the ungodly urges of untamed urges",
    "Venturing into the vile vortex of villainous vices",
    "Wallowing in the wicked whims of wild wantonness",
    "X-raying the x-rated underbelly of xanadu",
    "Yielding to the yowling yens of yearning",
    "Zooming through the zany zone of zealous depravity",
    "Delving into the grimy depths of self-love",
    "Exploring the cavern of carnal curiosity",
    "Feeding the insatiable beast of personal pleasure",
    "Tackling the slippery slope of solo satisfaction",
    "Summoning the mighty geyser of bodily bliss",
    "Venturing into the filthy lair of lustful cravings",
    "Diving into the seedy underbelly of self-stimulation",
    "Setting sail on the high seas of unbridled urges",
    "Unlocking the gates to the forbidden palace of passion",
    "Rubbing one out in the filthy alley of secret indulgence",
    "Riding the wave of shameless self-gratification",
    "Conquering the mountain of untamed ecstasy",
    "Journeying into the dank dungeon of debauched delight",
    "Unleashing the torrent of sinful sensations",
    "Breaking free from the chains of self-restraint",
    "Battling the dark forces of lustful temptation",
    "Traversing the valley of x-rated excess",
    "Launching the rocket of raunchy rapture",
    "Stroking the flame of guilty pleasure",
    "Erupting the volcano of ungodly urges",
    "Slapping the salami in the sordid sanctuary of sin",
    "Whacking the weasel in the wicked garden of delight",
    "Visiting the sleazy circus of secret desires",
    "Manipulating the joystick in the game of solitary sin",
    "Venturing into the filthy forest of forbidden fantasies",
    "Scaling the tower of taboo temptations",
    "Corralling the wild stallion of carnal impulses",
    "Unraveling the tangled web of dirty dreams",
    "Feasting on the forbidden fruit of lustful longings",
    "Plumbing the depths of obscene obsessions",
    "Embracing the dark side of reckless abandon",
    "Probing the recesses of ribald reprieve",
    "Fighting the battle of carnal conquest",
    "Indulging in the seedy buffet of shameless self-pleasure",
    "Unearthing the treasures of licentious liberation",
    "Drowning in the cesspool of primal passions",
    "Deciphering the cryptic code of carnal cravings",
    "Releasing the kraken of lustful levity",
    "Wrestling with the twisted tendrils of desire",
    "Getting down and dirty in the trenches of temptation",
    "Penetrating the fortress of fleshly fantasies",
    "Feeling the heat in the inferno of indulgence",
    "Grasping the reins of hedonistic hunger",
    "Plucking the strings of lascivious longing",
    "Battling the hydra of hormonal hankerings",
    "Tempting fate in the gauntlet of guilty gratification",
    "Chasing the dragon of decadent daydreams",
    "Facing the music in the symphony of sinful satisfaction",
    "Milking the python in the den of depravity",
    "Tasting the ambrosia of forbidden fruit",
    "Riding the wave of unbridled lust",
    "Fording the river of filthy fantasies",
    "Conjuring the spirits of salacious sorcery",
    "Reveling in the abyss of ungodly gratification",
    "Taming the beast of unbridled desire",
    "Exploring the catacombs of carnal corruption",
    "Escaping into the labyrinth of lascivious pleasures",
    "Plunging headfirst into the pool of primal passion",
    "Delving into the dark side of solitary satisfaction",
    "Toying with the fires of debased desire",
    "Unlocking the door to the hidden chamber of lust",
    "Paddling the canoe of carnal chaos",
    "Dissecting the anatomy of deviant delight",
    "Roaming the wasteland of wanton wickedness",
    "Scaling the walls of the forbidden fortress",
    "Setting sail on the stormy seas of sexual discovery",
    "Summoning the tempest of self-pleasing sins",
    "Traversing the uncharted territory of taboo temptations",
    "Unveiling the mysteries of malevolent indulgence",
    "Vanquishing the demons of debauched desires",
    "Wading through the murky waters of sinful sensations",
    "X-raying the depths of x-rated ecstasy",
    "Yielding to the siren call of lustful yearnings",
    "Zigzagging through the maze of zealous gratification",
    "Jacking the beanstalk in the garden of earthly delights",
    "Exploring the mine shaft of hidden treasures",
    "Descending into the abyss of carnal chaos",
    "Stroking the salamander in the pit of forbidden passion",
    "Tickling the underbelly of lewd longing",
    "Embracing the darkness in the chamber of secrets",
    "Walking the tightrope of unbridled passion",
    "Delighting in the carnal carnival of lustful pursuits",
    "Peeling back the layers of lascivious secrets",
    "Uncovering the hidden gems of self-indulgence",
    "Nibbling the forbidden fruit of naughty nirvana",
    "Summoning the spirits of sexual sorcery",
    "Discovering the sunken treasures of solo satisfaction",
    "Navigating the tawdry tunnels of temptation",
    "Plunging into the depths of debauched desire",
    "Unlocking the Pandora's box of primal passions",
    "Flipping the switch in the den of deviant delights",
    "Emerging victorious in the battle of bodily bliss",
    "Reveling in the glory of hedonistic hunger",
    "Scaling the heights of salacious satisfaction",
    "Following the rabbit down the hole of unbridled curiosity",
    "Dancing with the devil in the moonlit garden of lust",
    "Unleashing the tsunami of self-fulfillment",
    "Drilling for oil in the well of carnal cravings",
    "Launching the missile of self-gratification",
    "Feeding the beast in the den of depravity",
    "Exploring the cave of forbidden fantasies",
    "Riding the roller coaster of personal pleasure",
    "Chasing the dragon of debauched delight",
    "Stirring the pot of lustful longings",
    "Wrestling the anaconda of primal passions",
    "Discovering the lost city of self-indulgence",
    "Plumbing the depths of erotic excess",
    "Dissecting the entrails of carnal chaos",
    "Excavating the mine of sinful sensations",
    "Fishing in the cesspool of secret desires",
    "Harvesting the seed of unbridled ecstasy",
    "Juggling the jewels of depraved debauchery",
    "Kindling the fire of taboo temptations",
    "Levitating the spirits of hedonistic horrors",
    "Mining the veins of obscene obsessions",
    "Orbiting the dark side of lustful longing",
    "Peeling the layers of x-rated rapture",
    "Quenching the thirst of deviant delight",
    "Racing the clock of erotic escapades",
    "Stoking the furnace of forbidden fruit",
    "Taming the wild stallion of ungodly urges",
    "Uprooting the tree of lascivious liberation",
    "Voyaging into the vortex of villainous vices",
    "Wandering the desert of dirty dreams",
    "Xeroxing the blueprint of sexual sorcery",
    "Yanking the chain of carnal corruption",
    "Zipping through the jungle of zealous gratification",
    "Climbing the mountain of lustful levity",
    "Descending into the dungeon of personal passion",
    "Embarking on the conquest of uncharted territory",
    "Flipping the switch on the machine of desire",
    "Grinding the gears of guilty pleasure",
    "Unlocking the treasure chest of secret sins",
    "Inflating the balloon of bodily bliss",
    "Mapping the landscape of erotic exploration",
    "Opening the floodgates of sinful satisfaction",
    "Plundering the riches of lascivious longings",
    "Questioning the boundaries of carnal curiosity",
    "Reveling in the playground of raunchy rapture",
    "Submerging into the ocean of debased desire",
    "Traversing the swamp of taboo temptation",
    "Unraveling the mystery of lewd levity",
    "Venturing into the catacombs of carnal conquest",
    "Whipping up a storm of salacious satisfaction",
    "X-raying the depths of x-rated excess",
    "Yodeling in the valley of yearning",
    "Zapping the circuits of zealous depravity",
    "Walking the tightrope of randy recklessness",
    "Setting fire to the powder keg of passion",
    "Awakening the beast in the lair of lust",
    "Breaching the dam of bodily boundaries",
    "Chasing the wind of wanton wickedness",
    "Deconstructing the puzzle of primal passions",
    "Entertaining the guests in the house of hedonism",
    "Flipping the coin of forbidden fascinations",
    "Grasping the handle of guilty gratification",
    "Imbibing the elixir of erotic euphoria",
    "Jumping the shark of jaw-dropping perversion",
    "Kicking back in the lounge of lascivious leisure",
    "Liberating the genie of lewd liberation",
    "Melting the ice in the fire of carnal cravings",
    "Nurturing the seedling of naughty nirvana",
    "Overcoming the odds of obscene obsessions",
    "Playing the slots in the casino of sin",
    "Queuing the playlist of salacious songs",
    "Rumbling the engine of desire's hot rod",
    "Stirring the cauldron of self-serving sorcery",
    "Targeting the bullseye of titillating temptation",
    "Unwrapping the gift of unbridled urges",
    "Vandalizing the canvas of virtuous vices",
    "Witnessing the eruption of wicked whims",
    "Exposing the underbelly of xanadu",
    "Yearning for the yin and yang of yearning",
    "Zealously zipping through the zone of zestful delight",
    "Discovered in the midst of the sweaty, single-handed Olympics",
    "Caught red-faced while tuning the skin flute solo",
    "Interrupted during a scandalously private audience with the Pope",
    "Detected while fervently auditioning the silent hand puppet",
    "Busted during a clandestine meeting with the illustrious Palmela Handerson",
    "Caught red-handed performing the finesse-filled five finger ballet",
    "Stumbled upon during an embarrassingly hands-on seminar",
    "Accosted mid-way through the grueling arm wrestling tournament",
    "Surprised mid-moan while spelunking the hallowed trouser cave",
    "Caught in the act of practicing the secret handshake with gusto",
    "Discovered while fervently firing the flesh musket",
    "Busted while fervently engaging in self-service at the pleasure station",
    "Caught during a trip to the self-checkout aisle, no coupons needed",
    "Interrupted while eagerly taking matters into your own hands",
    "Found out during a private dance with nature, no audience required",
    "Stumbled upon during an intimate moment with a very personal inner peace",
    "Detected while performing a tantalizing magic trick with the wand",
    "Caught in the throes of doing the passionate one-handed tango",
    "Discovered while performing a spirited solo on the skin trumpet",
    "Caught in the jubilant throes of having a hand party",
]



