exports.starter = [
    "I feel like",
    "I'm",
    "I love",
    "Here I go again",
    "I can't stop",
    "I'm addicted to",
    "I have fun",
    "I got caught",
    "I spend all my time",
    "My dog saw me",
    "I never get sick of",
    "I spend all my time",
    "My grandma walked in on me",
    "The police officer saw me",
    "A scary clown was watching me",
    "I really enjoy",
    "I spend hours and hours",
    "I got fired for",
    "I got in trouble for",
    "I got high fived in court for",
    "I got sent to jail for",
    "It was worth going blind for",
    "In the bathroom at work someone walked in on this guy",
    "The manager at the restaurant was caught",
    "I saw my boss",
    "They saw our boss",
    "Even my grandpa likes"

]



exports.jackingOff = [
    "cutting a hole in my jorts in order to jerk my gerkin without people noticin",
    "cutting a hole in my jorts in order to jerk my gerkin without people noticin",
    "cutting a hole in my jorts in order to jerk my gerkin without people noticin",
    "cutting a hole in my jorts in order to jerk my gerkin without people noticin",
    "Going on a big date with Rosy Palms",
    "Adjusting my set",
    "Applying the slimy hand brake",
    "Attacking the one-eyed purple-headed warrior",
    "Auditioning the finger puppets",
    "Auditioning my hand puppet",
    "A round of backstroke roulette",
    "Bashing the Bishop",
    "Bashing the candle",
    "Beating off",
    "Beating the balogna",
    "Beating the bed flute",
    "Beating the Bishop",
    "Beating the dummy",
    "Beating the old man",
    "Beating the pud",
    "Beating the stick",
    "Beating my meat",
    "A plate of Beef-stroke-it-off",
    "Being a virtuoso of the skin flute",
    "Being my own best friend",
    "Biffing off",
    "Bleeding the weed",
    "Blowing the load",
    "Blowing my own horn",
    "Bludgeoning the beefsteak",
    "Bobbing my boloney",
    "Bopping Richard",
    "Bopping the bishop",
    "Bopping the bolgney",
    "Bopping the Bonzo",
    "Boxing the bald champ",
    "Boxing the clown",
    "Boxing the jesuit and getting cockroaches",
    "Boxing with Richard",
    "Buffing the bishop",
    "Buffing the banana",
    "Buffing the rifle",
    "Buggering my hand",
    "Burping the baby",
    "Burping the worm",
    "Buttering the corn",
    "Caning the vandal",
    "Capturing the bishop",
    "Charming the snake",
    "Checking for testicular cancer",
    "Cheesing off",
    "Choking Kojak",
    "Choking the bald guy until he pukes",
    "Choking the chicken",
    "Choking the sheriff and waiting for the posse to come",
    "Churning my butter",
    "Clamping the pipe",
    "Cleaning my rifle",
    "Clearing the snorkel",
    "Climbing the tree",
    "Climbing Mount Baldy",
    "Clobbering the Kleenex",
    "A game of Closet Frisbee",
    "Clubbing the clam",
    "Coating Prince William Sound with love oil",
    "Coming into my own",
    "Coming to grips with myself",
    "Cooking the cream of cock",
    "Corralling the tadpoles",
    "A Game of Couch hockey for one",
    "Cranking the love pump",
    "Cranking the angry monkey",
    "Cranking the slippery shank",
    "Crimping the floppy wire",
    "Crowning the drowsy king",
    "Cuddlin' the sour Kielbasa",
    "Cuffing the skinny carrot",
    "Dancing with Johnnie One-Eye",
    "Dating Miss Michigan",
    "Dating Rosie Palm and her five sisters",
    "Decongesting the weasel",
    "Defrosting the fridge",
    "Diddling",
    "Digging for change",
    "Digitally oscillating one's penis",
    "Doin' The Solitary Rhumba",
    "Doing a solo hand job",
    "Doing battle with the Purple Helmeted Warrior of Love",
    "Doing handiwork",
    "Doing It my Way",
    "Doing the five-knuckle shuffle",
    "Doing the human version of AUTOEXEC.BAT",
    "Doing the janitor thing",
    "Doing the knuckle shuffle on the ol' piss pump",
    "Doing the pork sword jiggle",
    "Doing the White Knuckler",
    "Doing my own thing",
    "Downing at the club (for members only)",
    "Draining the monster",
    "Draining the poisons from the building",
    "Driving the skin bus",
    "Dry humping the ottoman",
    "Dundering the devil-dolphin",
    "Electing the president",
    "Engaging in safe sex",
    "Escorting the one-eyed postal worker out of its denim cell",
    "Faxing Jimmy Dean",
    "Faxing the Pope",
    "Feeding the ducks",
    "Firing the flesh musket",
    "Firing the Surgeon General",
    "Fishing for zipper trout",
    "Fisting my mister",
    "Some Five-finger solo",
    "Five-knuckle-shuffle on the old piss pump",
    "A Little Five on one",
    "Flicking on over the thumb",
    "Flapping Takkie ",
    "Flaying the Emperor",
    "Flicking the bic",
    "Flipping the Bishop",
    "Flogging the bishop",
    "Flogging the dog",
    "Flogging the dolphin",
    "Flogging the dong",
    "Flogging the frog",
    "Flogging the hog",
    "Flogging the log",
    "Flogging the mule",
    "Flogging the salami",
    "Flogging my dumber brother",
    "A Flute solo",
    "Fly fishing",
    "Fondling the fig",
    "Freeing Willy",
    "Frosting the pastries",
    "Galloping the antelope",
    "Galloping the old lizard",
    "Genitalic stimulation via phallengetic motion",
    "Getting a date with Slick Mittens",
    "Getting a grip on things",
    "Getting a stiffy",
    "Getting chafed",
    "Getting off",
    "Getting the German soldier marching",
    "Getting the glue stick",
    "Getting to know myself",
    "Getting my palm read by Mister Softee",
    "Getting my palm red",
    "Getting my pole varnished",
    "Giving it a tug",
    "Giving myself a low five",
    "Glazing the donut",
    "Going a couple of rounds with ol' josh",
    "Going blind",
    "Going on a date with Handrea and Palmela",
    "Going on a date with Rosey Palm and the five daughters",
    "Going on Peewee's little adventure",
    "Grappling the gorilla",
    "Greasing the pipe",
    "Gripping the pencil",
    "Hacking the hog",
    "Hand Shandy",
    "Handy work",
    "Hanging the old man",
    "Hard labor",
    "Having a ball",
    "Having a conversation with the one-eyed trouser snake",
    "Having a date with Fisty Palmer",
    "Having a date with Rosie Palm and her five sisters",
    "Having a ham shank",
    "Having a J. Arthur",
    "Having a one-night-stand with myself",
    "Having a Sherman",
    "Having a tug",
    "Having a tug-of-war with the cyclops",
    "Having an arm-wrestle with my one-eyed vessel",
    "Having dinner",
    "Having it off",
    "Having sex with someone you love",
    "Hitchhiking to heaven",
    "Hitchhiking underneath the big top",
    "Holding my own",
    "Holding the sausage hostage",
    "Honing the cone",
    "Hugging the hog",
    "Humping the hose",
    "Ironing some wrinkles",
    "Jack hammering",
    "Jacking off",
    "Jazzing myself",
    "Jerkin' the gherkin",
    "Jerking Jamby",
    "Jerking off",
    "Jerking the turkey",
    "Jerking yanking daisy-chaining",
    "Jizzlobbing",
    "Juggling the coullions",
    "Just jerkin' it",
    "Kicking seamen",
    "Kicking my roommate out for five to ten minutes to 'call my parents'",
    "Killing it",
    "Kneading my knockwurst.",
    "Knuckle shuffle on the ol' piss pump",
    "Knuckling the bone",
    "La veuve poignet",
    "Launching the hand shuttle",
    "Looking for ticks",
    "Loping the mule",
    "Loving the muppet",
    "Lubing the Tube",
    "Making a foreskin cone",
    "Making friends with Big Ed",
    "Making instant pudding",
    "Making the bald man puke",
    "Making the scene with the magazine",
    "Making vanilla jism shakes",
    "Making myself at home",
    "Mangling the midget",
    "Manipulating the mango",
    "Manning the cockpit",
    "Manual labor",
    "Manual override",
    "Master bacon",
    "Meeting Mary Palm and her five sisters",
    "Meeting Rosie Hancock",
    "Meeting with Mother Thumb and her four daughters",
    "Milking one's self",
    "Milking the bull",
    "Milking the cow",
    "Milking the lizard",
    "Milking the moose",
    "Milking the weasel",
    "Minding my own business",
    "Molesting the mole",
    "Mounting a corporal and four",
    "Much goo about nothing",
    "Nerking my throbber",
    "Oiling the glove",
    "Onan's Olympics",
    "Onanism",
    "Blasting a One gun salute",
    "A One man show",
    "One off the wrist",
    "Packing my palm",
    "Paddling the pickle",
    "Painting the ceiling",
    "Painting the pickle",
    "Painting the walls",
    "Palming the calm",
    "Peelin' some chiles",
    "Peeling the banana",
    "Peeling the carrot",
    "Performing a self-test",
    "Performing diagnostics on my ManTool",
    "Perling the oyster",
    "Petting the lizard",
    "Phoning the czar",
    "Pipping the pumpkin",
    "Playing a little five-on-one",
    "Playing a one-stringed guitar",
    "Playing in a one-man show",
    "Playing Peek-A-Boo With Mr. Johnson",
    "Playing peekaboo",
    "Playing pocket pinball",
    "Playing pocket pool",
    "Playing tag with the pink torpedo",
    "Playing the flesh flute",
    "Playing the one-stringed melody",
    "Playing the skin flute",
    "Playing tug-o-war with the cyclops",
    "Playing Uno",
    "Playing with the spitting llama",
    "Playing with my turtle",
    "Pleasing my pisser",
    "Plunking my twanger",
    "Some Pocket pinball",
    "Some Pocket pool",
    "Pole vaulting",
    "Polishing Percy in my palm",
    "Polishing the beak",
    "Polishing the family jewels",
    "Polishing the helmet",
    "Polishing the rocket",
    "Polishing the sword",
    "Popping a nut",
    "Popping the cork",
    "Pounding off",
    "Pounding the bald-headed moose",
    "Pounding the pud",
    "Pounding my flounder",
    "Preparing the carrot",
    "Priming the pump",
    "Pud wrestling",
    "Pulling off",
    "Pulling rank",
    "Pulling the bologna pony",
    "Pulling the carrot",
    "Pulling the Colonel Sanders Heimleich Manuever",
    "Pulling the cord",
    "Pulling the five-knuckle shuffle",
    "Pulling the goalie",
    "Pulling the handbrake",
    "Pulling the pole",
    "Pulling the Pope",
    "Pulling the weed",
    "Pulling the wire",
    "Pulling my goalie",
    "Pulling my own leg",
    "Pulling my prick",
    "Pulling my pud",
    "Pulling my taffy",
    "Pummeling the priest",
    "Pumping cream",
    "Pumping the electric goo gun",
    "Pumping the gas at the self-service island",
    "Pumping the python",
    "Pumping the stump",
    "Punchin' the munchkin",
    "Punching the clown",
    "Punching the munchin",
    "Punishing Percy in the palm",
    "Punishing the Pope",
    "Qualifying in the testicular time trial",
    "Raising the mainsail",
    "Ramming the ham",
    "Rapid one arm pull-ups",
    "Reading poetry",
    "Relieving tension",
    "Riding the great white knuckler",
    "Rolling my own",
    "Romancing the bone",
    "Romeo and Himself",
    "Roping the pony",
    "Roping the Pope",
    "Roughing up the suspect",
    "Rubbing off",
    "Rubbing one out",
    "Rubbing the magic one-eyed wonder weasel",
    "Rubbing the pink eraser",
    "Rubbing the rod",
    "Running off a batch by hand",
    "Running the cheeta",
    "Sacrificing sperm to the god of lonely nights",
    "Sanding wood",
    "Saying a private prayer in the Church of the First Holy Monkey",
    "playing Schnauzer Shuffleboard",
    "Scouring the tower of power",
    "Scraping my horn",
    "Scratchin the itch",
    "Se faire les cinq doigts de la main",
    "A Secret handshake",
    "Engaging in Self abuse",
    "A little Self-induced penile regurgitation",
    "Some Self-inflicted intercourse",
    "Shaking hands with Abraham Lincoln",
    "Shaking hands with Jack McNasty",
    "Shaking hands with Mr. Happy",
    "Shaking Hands with Mr. President",
    "Shaking hands with the general",
    "Shaking hands with the midget",
    "Shaking hands with the unemployed",
    "Shaking hands with the wife's best friend",
    "Shaking hands with my John Thomas",
    "Shaking hands with my wife's best friend",
    "Shaking hands with Yul Brenner",
    "Shaking the bottle",
    "Shaking the dice",
    "Shaking the hand of the self-employed",
    "Shaking the sauce",
    "Shaking the sausage",
    "Shaking the snake",
    "Shanking",
    "Shellacking the shellaleigh",
    "Shemping the hog",
    "Shifting gears",
    "Shining the helmet",
    "Shining the pork sword",
    "Shining my pole",
    "Shooting skeet",
    "Shooting flies",
    "Shooting for the moon",
    "Shooting putty at the moon",
    "Shooting tadpoles at the moon",
    "Shooting my wad",
    "Shucking my corn",
    "Slaking the bacon",
    "Slamming the ham",
    "Slamming the hammer",
    "Slamming the salami",
    "Slamming the salmon",
    "Slamming the spam",
    "Slapping the big-nosed Rasta man",
    "Slappin the purple headed yogurt pistol",
    "Slapping high fives with Yul Brynner",
    "Slapping it",
    "Slapping pappy",
    "Slapping the carrot",
    "Slapping the clown",
    "Slapping the donkey",
    "Slapping the FleshGopher",
    "Slapping the pud",
    "Slapping the salami",
    "Sliding up and down my tube",
    "Slinging the jelly",
    "Smacking the oompa loompa",
    "Smacking the salami",
    "Smacking the weasel",
    "Smacking-off",
    "Snapping one off",
    "Snapping the carrot",
    "Snapping the monkey",
    "Snapping the rubber",
    "Snapping the whip",
    "A Solo flight",
    "A Solo marathon",
    "Some Solo sex",
    "Spanking Cheetah",
    "Spanking Elvis",
    "Spanking Frank",
    "Spanking the bishop",
    "Spanking the monkey",
    "Spanking the salami",
    "Spanking the wank",
    "Spit-polishing the purple helmet",
    "Spunking",
    "Squeezing the cheese",
    "Squeezing the cream from the flesh Twinkie",
    "Squeezing the juice",
    "Squeezing the lemon",
    "Squeezing the weasel",
    "Squeezing my cheese-dog",
    "A little Stinky pinky",
    "Stirring the batter",
    "Stirring the yogurt",
    "Strainin' the main vein",
    "Strangling the Serpent",
    "Striking the pink match",
    "Stroking it",
    "Stroking off",
    "Stroking the dog",
    "Stroking the lizard",
    "Stroking the mole",
    "Stroking the one-eyed burping gecko",
    "Stroking the satin-headed serpent",
    "Stroking the squirmin' German",
    "Stroking the wiener",
    "Stroking my poker",
    "Stroking my twinkie",
    "Taking a nap",
    "Taking a shake break",
    "Taking Herman to the circus",
    "Taking matters into my own hands",
    "Taking ol' one eye through the fly",
    "Taking part in population control",
    "Taking some time off",
    "Taking the Jocelyn Elders Midterm",
    "Taking the monster for a one-armed ride",
    "Talking quietly to myself",
    "Taming the shrew",
    "Taunting the one-eyed weasel",
    "Teasing the weasel",
    "Teasing the weenie",
    "Tenderizing the meat",
    "Tenderizing the tube steak",
    "A Testicular tensile strength test",
    "Testing the testicles",
    "Testing my batteries",
    "That crazy hand jive",
    "The art of Unisex",
    "The Colonel Sanders Heimleich Maneuver",
    "The five knuckle shuffle on the old piss pipe",
    "Thrapping",
    "Throwing",
    "Throwing one",
    "Thumping the pump",
    "Ticklewigglejigglepickle",
    "Tickling my fancy",
    "Tickling the ivory",
    "Tickling the one-eyed weasel",
    "Tickling the pickle",
    "Tonking",
    "Torkin' the fork",
    "Torturing the tentacle",
    "Tossing off",
    "Tossing the salad",
    "Tossing the snag",
    "Tossing the turkey",
    "Tossing yogurt",
    "Treating myself right",
    "Trouser snake CPR",
    "Tugging the slug",
    "Tugging the tapioca tube",
    "Tuning my horn",
    "Turning Japanese",
    "Twanging the wire",
    "Tweaking my twinkie",
    "Twisting my crank",
    "Twisting my tool",
    "Unloading the gun",
    "Using the Force on Darth Vader",
    "Varnishing the flagpole",
    "Violating the hedge-hog",
    "Visiting Rosy Palm and her five daughters",
    "Wacking off",
    "Wacking the one-eyed worm",
    "Wacking the weasel",
    "Wacking the willie",
    "Waking the dead",
    "Waking Wee Willie Wonka",
    "Walking the dog",
    "Walking the plank",
    "Walking the snake",
    "Waltzing with Willy",
    "Wanking",
    "Wanking with the one-eyed wonder weasel",
    "Washing the meat",
    "Waving the Magic Wand",
    "Waxing the car",
    "Waxing the carrot",
    "Waxing the dolphin",
    "Waxing my surfboard",
    "Whackin the weasel",
    "Whacking it",
    "Whacking off",
    "Whacking Willy",
    "Whipping off",
    "Whipping the bishop",
    "Whipping the dummy",
    "Whipping the one-eyed trouser snake",
    "Whipping the rat",
    "Whipping the stiff",
    "Whipping the wire",
    "Whipping up some sour cream",
    "Whipping willy the one-eyed wonder-worm",
    "Whipping my dripper",
    "White-water wristing",
    "Whittling the stick",
    "Whizzing jism",
    "Windsurfing on Mount Baldy",
    "Wonking my conker",
    "Wonking my donk",
    "Workin' out a stiff joint",
    "Working off",
    "Working off a batch",
    "Wrestling the eel",
    "Wrestling the one-eyed monster",
    "Wrestling the purple headed warrior",
    "Wrestling with the bald champ",
    "Wringing out my rope",
    "doing Wrist aerobics",
    "Yanking off",
    "Yanking the crank",
    "Yanking the yoyo",
    "Yanking my plank",
    "Boxing my clown",
    "Punching the munchkin",
    "Wanking",
    "Polishing my sword",
    "Some Backstroke roulette",
    "Bashing the candle",
    "Tipping off the inspector",
    "Tossing the snag",
    "Tossing the turkey",
    "Tossing yogurt",
    "Tugging the slug",
    "Twanging the wire",
    "Tweaking my Twinkie",
    "Twisting my crank",
    "Unleashing the alabaster yak",
    "Unloading the gun",
    "Unpacking the moving van",
    "Varnishing the flagpole",
    "Varnishing the banister",
    "Visiting with Papa Smurf",
    "Waking the dead",
    "Walking the dog",
    "Walking the plank",
    "Walking a mile in Mr. Wigglies shoes",
    "Wallowing in self pity",
    "Wanking with the one-eyed wonder weasel",
    "Washing the meat",
    "Waxing the Buick",
    "Waxing the carrot",
    "Waxing the dolphin",
    "Waxin n Milkin",
    "Whacking it",
    "Whacking the weasel",
    "Whacking my Willy",
    "Whipping the dummy",
    "Whipping the one-eyed trouser snake",
    "Whipping the one-eyed worm",
    "Whipping the rat",
    "Whipping the stiff",
    "Whipping the wire",
    "Whipping up some sour cream",
    "Whipping my dripper",
    "Whitewashing with Huck and Tom",
    "Whittling the stick",
    "Wiggling my walrus",
    "Windsurfing on Mount Baldy",
    "Wonking my conker",
    "Working things out",
    "Working at my own speed",
    "Working late at the office",
    "Working up a foamy lather",
    "Working without Annette",
    "Wrestling the dragon",
    "Wrestling the eel",
    "Wrestling with the bald champ",
    "Wringing out my rope",
    "Some Wrist aerobics",
    "Yanking the crank",
    "Yanking the yo-yo",
    "Yanking my plank",
    "Evicting the testicular squatters",
    "Evicting the testicular squatters",
    "Pooping the pud",
    "Rearranging the deck chairs",
    "Lavishly caressing my own thighs",
    "Spurting into my own hand",
    "Tossing the bagel",
    "Feeding my own dogs",
    "Borrowing Mrs. Frump's bicycle",
    "Riding an automobile",
    "Crushing it to bits",
    "Whipping the beaver",
    "Socking myself in the face with the duster!",
    "Stroking my flabby gut with my belly button lint filter",
    "Warming my bumblebee hive in its nest",
    "Flattening the pillow",
    "Snatching back my hand and going 'I told you so'",
    "Scalding my own back yard",
    "Lacing up the white sneakers",
    "Bouncing the cat",
    "Punching myself in the nose",
    "Lying on the lavender pillows",
    "Thawing the goose on a saran wrap",
    "Whipping the wimp",
    "Cobbal-binging the cussword",
    "Smelling my shirt collar on a rainy day",
    "Nailing my best friend to the shed to rot",
    "Screwing the scullery maid",
    "Blowing up the big red one",
    "Flipping the pork pie",
    "Squirting some mustardy",
    "Sinking fast on this one",
    "Smacking the toaster",
    "Tossing potatoes on high alert",
    "Making the money work",
    "Flexing my ham hock",
    "Busting a gut and going for a walk on Mars",
    "Mucking the meter",
    "Going in and seeing a lady doctor named Miss Jane for the old lady cure",
    "Playing doctor",
    "Making her a man again",
    "Making a meal out of it",
    "Rolling around on a spongecake of cocaine",
    "Catching the canary",
    "Being a chicken wing",
    "Squeezefucking",
    "Cracking a safe",
    "Rubbing one's tuchus",
    "Gulping the goop",
    "Conducting the orchestra",
    "Beef-a-rooneying",
    "Rubbing one's tuchus",
    "Carrying my balsam root to hell",
    "Feeding the chicken",
    "Going out shopping with myself",
    "Frownie, go fishing",
    "Winkie, go dancing",
    "Pretzel face face, make it snuggly snortable facey go go go",
    "Shakin', a shaking' hand from a shake",
    "A jingaling and a singaling from my lips",
    "Whipping and wringing with its little hand",
    "One little finger to pinch one little tinge. YIPPee!",
    "Rubbing the borsalino.",
    "Yawning over yon bonfire on my tail",
    "Rising with my right hand my friend. You're at my behest. And in a minute, you can waddle on up the shore, a bit faster too you wannit be...",
    "And wah, my dung shall fly as thy name calls me home again?",
    "Blowing myself silly without having the courage to touch myself",
    "Sliding an elbow with one-legged Bob, a maimed-from-behind lover",
    "Sailing on the high seas",
    "Tucking Tinky-Tinky into bed",
    "Squashing my pride",
    "Fending off the flys on the toilet",
    "Feeding the hunk-o-meat, that sweet hunk-o-meat",
    "Feeding the pigeons",
    "Feeding my wacky friend, squirrel-style (tiny but perfectly edible morsel)",
    "Slapping the purple cow's milk bag",
    "Gentle massaging for the ladybug ladybot (but don't let her bite)",
    "Facing my true colors",
    "Fingeling my finicky fizzbuckets",
    "Bending the knee to the great cheese curds of lore for the next one million zillion billion billion years",
    "Thieving eggs from my own backyard free range chicken coop",
    "Chowing down on my own cooking",
    "Gardening with my biker budgie and the one eyed sailor at the pet store",
    "Whack-a-doodle-doo-ing in my palm",
    "Throwing some cream on it",
    "Jailing the worm",
    "Stroking Rosalinda's daffodil bush",
    "Blubbering the baby seal",
    "Beating the bean drum at the county fair",
    "Climbing the tree of happiness",
    "Flogging the log",
    "Killing the one-legged cat with the rooster you got at the bazaar for two dollars",
    "Paddling across the pickle pond with a floating boat. Make sure to save a bucket for catfish and pickles!",
    "Slobbing down raw milk straight from the carton",
    "Just doing some quick math",
    "Dusting off the old furniture",
    "Dismantling the paddy wagon",
    "Watching Fist Freddy and Farkie Fleezie petting their giraffe Alex",
    "Dipping the sausage",
    "Tickling a tittie and pulling off five more to go with it",
    "Dive-bombing without diving or bombing",
    "Rolling a fat one",
    "Pickin' up some hottie in the parking lot, just for sport",
    "Swallowing the one that got away",
    "Making love with your first and last date",
    "Sniping the banana shooter",
    "Pumping the ducky",
    "Going fishing with old Jack Horner",
    "Stuffing the snail",
    "Stroking the snake",
    "Taking the one-armed cruise to paradise",
    "Having a rodeo with the midget",
    "Stirring up the yogurt",
    "Laying the smack on the snicker",
    "Hobbling the mule",
    "Beating the bologna",
    "Stretching the string",
    "Playin' with the one-eyed wonder weasel",
    "Choking the gimp",
    "Rubbing the salami out in the cold night air",
    "Dancing with the wiggler",
    "Shaking that pimp daddy head, dawg... Chill..",
    "Munching some meat",
    "Scratching the lottery",
    "Rubber-banding myself in pleasure knots",
    "Painting myself pink like my pet duck, Fanny",
    "Fiddling on the roof",
    "Pulling a rabbit from my magic hat",
    "Pouring gasoline on old Ed's flaming lawn",
    "Acing the interview with myself",
    "Adjusting the minute hand on the old grandfather clock",
    "Practicing my tennis serve with no one around",
    "Hitting the gong. Behold, the Emperor!",
    "Dancing in the rain",
    "Banging your drum solo until the neighbors complain",
    "Hosting a private pity party for one with your little captain as the DJ",
    "Becoming your own porn director and star of the show",
    "Treating Palmela Handerson to a meal at the finest fast food joint in town",
    "Spanking the bishop like you're trying to hit a home run",
    "Buffing the bald-headed golfer until it shines like a diamond",
    "Congratulating yourself for being the world champion of self-love",
    "Taking the law into your own hands and punishing your naughty bits",
    "Touring the international waters of your one-eyed monster like a seasoned sailor",
    "Fulfilling your life's mission of being the best friend your little buddy ever had",
    "calling for reinforcements like a general in a battle against boredom",
    "Achieving a personal best in the one-man Olympic games of self-pleasure",
    "Creating a masterpiece on the ceiling like a modern-day Michelangelo",
    "Jazzing up the flesh flute like a master of improvisation",
    "Taking a ride on the self-love express to orgasm central",
    "Scoring a perfect 10 on the pleasure scale like a judge in a beauty pageant",
    "Riding the knucklehead like a professional bull rider at the rodeo",
    "Gazing upon the sights of the self-love strip like a tourist in Vegas",
    "Crafting your own DIY satisfaction kit like a skilled artisan",
    "Playing a one-man game of five-finger fillet with your sausage while wearing a VR headset",
    "Hosting a solo salsa party for your little captain",
    "Juggling your joystick while watching vintage 70s porn",
    "Taking Palmela Handerson out for a fancy dinner and treating her like a queen",
    "Spanking the bishop like a naughty schoolboy hiding from his mom",
    "Polishing the family jewels like they're the Hope diamond",
    "Shaking hands with the unemployed and congratulating them on their free time",
    "Taking matters into your own hands like a cowboy in the Wild West",
    "Visiting the one-eyed monster like a tourist in a foreign land",
    "Making your little friend happy like it's your mission in life",
    "Calling for backup like a WW2 soldier in the trenches",
    "Beating your own high score like a pro gamer going for a world record",
    "Painting the ceiling like Michelangelo painting the Sistine Chapel",
    "Playing the flesh flute like a virtuoso jazz musician on stage",
    "Taking the self-love train to Pleasureville like a Disney ride for adults",
    "Scoring a hole in one like a golfer aiming for the championship",
    "Mounting the knucklehead like a cowboy riding a bucking bronco",
    "Rubbernecking like a curious tourist in Vegas",
    "Doing some handiwork like a crafty DIY enthusiast",
    "Going solo on stage like a famous singer in a sold-out concert",
    "Taking a trip to Pleasure Island like Pinocchio looking for some fun",
    "Auditioning for the one-man band like a rockstar on a reality show",
    "Painting the town red like a wild party animal on New Year's Eve",
    "Tapping your own maple syrup like a Canadian farmer on a cold winter day.",
    "Doing the one-man tango",
    "Having a solo salsa session",
    "Juggling the joystick",
    "Going on a date with Palmela Handerson and a penny in my ass",
    "Spanking the bishop like he's a nasty slut",
    "Polishing the family jewels",
    "Shaking hands with the unemployed",
    "Taking matters into your own hands",
    "Visiting the one-eyed monster",
    "Making your little friend happy",
    "Calling for backup",
    "Beating your own high score",
    "Painting the ceiling",
    "Playing the flesh flute",
    "Taking the self-love train",
    "Scoring a hole in one",
    "Mounting the knucklehead",
    "Rubbernecking on a hot load",
    "Doing some handiwork with my mandiwork",
    "Going solo on stage with my love bazooka",
    "Taking a trip to pleasure island",
    "Auditioning for the one-man band",
    "Painting the town white with bradford pears",
    "Tapping your own maple syrup",
    "Spoiling the catch",
    "Decapitating the insect",
    "Slathering the loaf",
    "Swapping the nappy",
    "Inhaling the foot garment",
    "Obliterating the arthropod",
    "Hydrating the foliage",
    "Plucking the decayed produce",
    "Racing the lethargic gastropod",
    "Exaggerating the froth",
    "Polishing the ol' microphone",
    "Engaging in some high-five diplomacy",
    "Conducting a one-man band",
    "Choking the sherpa guiding you up the mountain",
    "Supercharging the serpent",
    "Introducing the monkey to martial arts",
    "Taking the turkey on a rollercoaster ride",
    "Playing DJ on a human turntable",
    "Enjoying some 'me time' in your personal sanctuary",
    "Performing a one-man orchestra",
    "Unleashing the hog's inner road warrior",
    "Teaching the bishop some wrestling moves",
    "Giving the weasel a crash course in martial arts",
    "Tickling the ol' xylophone",
    "Reenacting Mission: Impossible with the gerbil",
    "Waxing poetic on the board of dreams",
    "Engaging in some self-serenading",
    "Remixing life's soundtrack",
    "Strumming the banjo like a rockstar",
    "Bopping the clown on the nose",
    "Pounding the metaphorical drum of life",
    "Getting acquainted with Sir Fluffington",
    "Venturing into DIY territory",
    "Introducing your salami to a symphony",
    "Going on a journey of self-discovery",
    "Navigating the high seas with the dolphin",
    "Perfecting your aim in the game of life",
    "High-fiving the primate within",
    "Guiding the tiger to the watering hole",
    "Cranking up life's volume to 11",
    "Navigating the meat spaceship through the universe",
    "Serenading the one-eyed snake",
    "High-fiving the hungry caterpillar",
    "Unleashing the mongoose on a wild adventure",
    "Tickling the fancy of your personal genie",
    "Wrestling the Loch Ness monster",
    "Hypnotizing the slithery serpent",
    "Serenading your flesh trumpet",
    "Painting a masterpiece with your solo brush",
    "Tangoing with the tiny dancer",
    "Taming the ham-balaya",
    "Scuba diving with a reluctant eel",
    "Hosting a symposium for one",
    "Challenging the wildling to an arm wrestling match",
    "Engaging in top-secret diplomatic relations",
    "Demonstrating the Kung Fu grip",
    "DJing the soundtrack of your dreams",
    "Hosting a one-hamster dance party",
    "Carving a lonely mountain range",
    "Traversing the desert of self-appreciation",
    "Ticking the tock of your inner clock",
    "Whispering secrets to the dragon",
    "Serenading the cactus in a marathon performance",
    "Juggling the lonely orbs of destiny",
    "Starring in a pilot episode for one",
    "Practicing ninjutsu with the shadow warrior",
    "Frolicking with the fiddly bits",
    "Releasing the Kraken of self-expression",
    "Flying solo on a magic carpet ride",
    "Orchestrating a one-man band of epic proportions",
    "Journeying to the center of the doughnut",
    "Riding the waves of solo synchronicity",
    "Plunging the depths of personal spelunking",
    "Paddling the canoe of cosmic exploration",
    "Jousting with the invisible unicorn",
    "Reigniting the flames of your inner phoenix",
    "Discovering the lost treasure of Atlantis",
    "Stargazing with your private telescope",
    "Mapping the landscape of your dreams",
    "Setting sail on the high seas of self-love",
    "Soaring solo in a spaceship of desire",
    "Rocking the dancefloor with the invisible partner",
    "Tickling the soul strings of your inner muse",
    "Scaling the peaks of personal Everest",
    "Launching a one-rocket mission to the moon",
    "Dancing the tango of self-expression",
    "Taming the wild stallion of independence",
    "Setting the stage for a one-act play",
    "Serenading yourself with sweet symphonies",
    "Dueling with the dragon of duality",
    "Feeding the flames of inner desire",
    "Unlocking the hidden vaults of passion",
    "Charting a course for personal paradise",
    "Navigating the labyrinth of self-discovery",
    "Waltzing with the winds of whimsy",
    "Climbing the heights of hypnotic harmony",
    "Traversing the wilderness of want",
    "Whispering sweet nothings to your egotistical elf",
    "Bathing in the oasis of self-adoration",
    "Skipping stones across the sea of self-satisfaction",
    "Scaling the canyon walls of lonely euphoria",
    "Hiking the trails of tantalizing temptation",
    "Embarking on a voyage of velvety victory",
    "Pouncing on the prey of personal pleasure",
    "Plunging the watery depths of aquatic adventure",
    "Diving headfirst into the pool of personal potential",
    "Fishing for compliments in a sea of self-assurance",
    "Sipping from the chalice of cheeky charm",
    "Rowing through the rapids of rowdy rapture",
    "Soaking in the rays of righteous reflection",
    "Dancing through the desert of delightful delirium",
    "Scaling the staircase of sensual satisfaction",
    "Casting a dreamy spell with the wand of whimsical wizardry",
    "Gliding gracefully through the galaxy of grandeur",
    "Strolling the streets of sultry satisfaction",
    "Skipping along the shores of silken serenity",
    "Parading with pride through personal pomp and circumstance",
    "Jumping for joy in the jubilant jungle",
    "Stuffing the turkey of self-fulfillment",
    "Turning up the heat on the hot plate of hedonism",
    "Reenacting the moon landing with a personal astronaut",
    "Performing a secret handshake with your inner con artist",
    "Conducting a private TED Talk for an audience of one",
    "Operating a solo jackhammer at the construction site of pleasure",
    "Driving the getaway car in a one-man heist",
    "Sweeping the chimney of your inner workshop",
    "Preparing a romantic dinner for the chef within",
    "Breaking out of the prison of self-restraint",
    "Fishing for compliments in the pond of personal gratification",
    "Hosting a one-man baseball game in the stadium of self",
    "Playing a game of one-on-one with your own MVP",
    "Going undercover as a solo private investigator",
    "Serving up a self-appreciation buffet in the kitchen of desire",
    "Leaping across rooftops as your own parkour master",
    "Mastering the game of solitaire in the casino of self-indulgence",
    "Taking a scenic detour on the road to self-satisfaction",
    "Embarking on an archaeological dig of personal passion",
    "Jumpstarting the engine of your heart's hot rod",
    "Scaling the ladder of self-adulation like a high-rise window cleaner",
    "Conducting a top-secret experiment in your personal laboratory",
    "Performing a magic trick for the illusionist within",
    "Gaming the system of self-acceptance with a winning play",
    "Pitching a perfect game to the champion within",
    "Embarking on a solitary spelunking adventure into caverns of carnality",
    "Auditioning for the starring role in your own blockbuster",
    "Dueling with your inner fencing master in a match of self-discovery",
    "Flipping the pancakes of pleasure at the diner of desire",
    "Peeling back the layers of your personal masterpiece",
    "Rowing the gondola of self-adoration through the canals of satisfaction",
    "Breaking into the vault of your hidden treasures",
    "Taking center stage in a one-person performance",
    "Crafting a work of art with the tools of self-exploration",
    "Mowing the lawn of personal satisfaction with a meticulous touch",
    "Exploring the jungle of your heart's desires like a daring adventurer",
    "Navigating the ocean of opportunity like a fearless sea captain",
    "Swinging through the branches of the self-love tree",
    "Scaling the rooftop of your inner skyscraper",
    "Plunging into the deep end of self-adoration",
    "Arranging a rendezvous with your secret agent of self-discovery",
    "Revving the engine of personal achievement in a drag race for one",
    "Summoning the sewer serpent in a one-man excavation",
    "Conducting a symphony of smells in the orchestra pit of pungency",
    "Venturing deep into the gas chamber of gastric distress",
    "Wrestling the swamp monster of perspiration and poots",
    "Unleashing the bog beast from the depths of digestive doom",
    "Waiting in line at the world's worst porta-potty party",
    "Navigating the noxious labyrinth of aromatic annihilation",
    "Accidentally disturbing the ancient burial ground of expired tuna cans",
    "Teaching vile hygiene habits to a putrid posse of pooches",
    "Slogging through a swampy cesspool of discomfort and despair",
    "Juggling the jellyfish of underarm calamity",
    "Captaining the S.S. Stench on a voyage of olfactory offense",
    "Exploring the dank depths of the uncomfortable underbelly",
    "Secretly sharing a medically-inadvisable bean burrito",
    "Sampling the forbidden fruit from the tree of trouser tremors",
    "Discovering the lost city of Atlantis in your own armpits",
    "Cracking open the tomb of the undead babybel cheese wheel",
    "Setting sail on the good ship snot rocket",
    "Dancing a demonic jig on the skull-strewn shores of Stink Island",
    "Marrying the macabre in a one-person ceremony of frenzied flatulence",
    "Provoking the putrid with a dance of festering foot funk",
    "Gently caressing the cold, clammy skin of aquatic atrocity",
    "Releasing the infernal hordes of a thousand cheesy gym socks",
    "Summoning a symphony of sorrow from the depths of digestive despair",
    "Facing off against your own uncomfortable odiferous onslaught",
    "Scaling the Mount Everest of bodily emissions",
    "Navigating the terrain of treacherous toots",
    "Unmastering the art of queasy quivers and queasiness",
    "Skating on thin ice over a lake of sizzling sewage",
    "Digging through the ForbiddenForest of Fungal Fury",
    "Unraveling the yarn ball of gastrointestinal gaffes",
    "Playing barge master on a river of rancid repugnance",
    "Reeking of unspeakable umbrage as you venture through the Valley of Vile",
    "Disturbing the tectonic plates of tantrum-throwing tummies",
    "Poking the sleeping dragon of digestive disaster",
    "Commandeering a one-man submarine through a sea of seething sludge",
    "Fumbling in the dark for the source of the sinister stench",
    "Serenading yourself with the Siren's song of stomach-churning shame",
    "Taking the plunge into the abyss of abhorrent afflictions",
    "Tickling the tarantula of tasteless tactlessness and tumultuous torment",
    "Festerin' in the gumbo turmoil",
    "Unruly swamp trumpet playing",
    "Pungent bayou bellowing",
    "Barn dance crampfesting",
    "Quakin' cornpone convulsive shivering",
    "Howlin' holler shaming horning",
    "Gator-torn britches squirting",
    "Stiflin' smokehouse squirm dangling",
    "Sheep-shorn moonlight shuddering",
    "Weevil-riddled hullabalooing",
    "Wailin' crawfish calamity fixing",
    "from the noodle were Sordid grits discharging ",
    "Clandestine outhouse tangoing",
    "Peculiar possum persuasion didickting",
    "Dixie thunder uproaring",
    "Maddening catfish caressing",
    "Humid hare fandangoing",
    "Tar-touched travesty grenade throwing",
    "Secret sludge serenading",
    "Lonely levee breaks lamenting",
    "Fanboat flustering and fanfaring",
    "Whisperin' willow affliction delivering",
    "Cacklin' critter fiasco slobbering",
    "Cypress swamp surrender muffin",
    "Shriveling kudzu kerfuffle",
    "Currish cottonmouth capering",
    "Abysmal armadillo anguish collapsing in a puddle of oil",
    "Undignified voodoo vista mongoose shriveling",
    "Hot sauce hullaboo inside momma's house",
    "Jambalaya jittering",
    "Muggy mosquito masqueradomg",
    "Tattered tobacco tornado watching",
    "Musty magnolia hotdog dancing",
    "Decayin' delta dilemma diagnosing",
    "Confederate cackle catastrophizing",
    "Torrid town tremor boner",
    "Sultry night-night shenanigan jizz",
    "Sweaty cotillion in sweaty velvetine",
    "Ponderin' premature possum pandemonium",
    "Creole calamity canoodle explosion"
]