exports.starter = [
    "I feel like",
    "I'm",
    "I love",
    "Here I go again",
    "I can't stop",
    "I'm addicted to",
    "I have fun",
    "I got caught",
    "I spend all my time",
    "My dog saw me",
    "I never get sick of",
    "I spend all my time",
    "My grandma walked in on me",
    "The police officer saw me",
    "A scary clown was watching me",
    "I really enjoy",
    "I spend hours and hours",
    "I got fired for",
    "I got in trouble for",
    "I got high fived in court for",
    "I got sent to jail for",
    "It was worth going blind for"
]



exports.jackingOff = [
    "Going on a big date with Rosy Palms",
    "Adjusting my set",
    "Applying the slimy hand brake",
    "Attacking the one-eyed purple-headed warrior",
    "Auditioning the finger puppets",
    "Auditioning my hand puppet",
    "A round of backstroke roulette",
    "Bashing the Bishop",
    "Bashing the candle",
    "Beating off",
    "Beating the balogna",
    "Beating the bed flute",
    "Beating the Bishop",
    "Beating the dummy",
    "Beating the old man",
    "Beating the pud",
    "Beating the stick",
    "Beating my meat",
    "A plate of Beef-stroke-it-off",
    "Being a virtuoso of the skin flute",
    "Being my own best friend",
    "Biffing off",
    "Bleeding the weed",
    "Blowing the load",
    "Blowing my own horn",
    "Bludgeoning the beefsteak",
    "Bobbing my boloney",
    "Bopping Richard",
    "Bopping the bishop",
    "Bopping the bolgney",
    "Bopping the Bonzo",
    "Boxing the bald champ",
    "Boxing the clown",
    "Boxing the jesuit and getting cockroaches",
    "Boxing with Richard",
    "Buffing the bishop",
    "Buffing the banana",
    "Buffing the rifle",
    "Buggering my hand",
    "Burping the baby",
    "Burping the worm",
    "Buttering the corn",
    "Caning the vandal",
    "Capturing the bishop",
    "Charming the snake",
    "Checking for testicular cancer",
    "Cheesing off",
    "Choking Kojak",
    "Choking the bald guy until he pukes",
    "Choking the chicken",
    "Choking the sheriff and waiting for the posse to come",
    "Churning my butter",
    "Clamping the pipe",
    "Cleaning my rifle",
    "Clearing the snorkel",
    "Climbing the tree",
    "Climbing Mount Baldy",
    "Clobbering the Kleenex",
    "A game of Closet Frisbee",
    "Clubbing the clam",
    "Coating Prince William Sound with love oil",
    "Coming into my own",
    "Coming to grips with myself",
    "Cooking the cream of cock",
    "Corralling the tadpoles",
    "A Game of Couch hockey for one",
    "Cranking the love pump",
    "Cranking the angry monkey",
    "Cranking the slippery shank",
    "Crimping the floppy wire",
    "Crowning the drowsy king",
    "Cuddlin' the sour Kielbasa",
    "Cuffing the skinny carrot",
    "Dancing with Johnnie One-Eye",
    "Dating Miss Michigan",
    "Dating Rosie Palm and her five sisters",
    "Decongesting the weasel",
    "Defrosting the fridge",
    "Diddling",
    "Digging for change",
    "Digitally oscillating one's penis",
    "Doin' The Solitary Rhumba",
    "Doing a solo hand job",
    "Doing battle with the Purple Helmeted Warrior of Love",
    "Doing handiwork",
    "Doing It my Way",
    "Doing the five-knuckle shuffle",
    "Doing the human version of AUTOEXEC.BAT",
    "Doing the janitor thing",
    "Doing the knuckle shuffle on the ol' piss pump",
    "Doing the pork sword jiggle",
    "Doing the White Knuckler",
    "Doing my own thing",
    "Downing at the club (for members only)",
    "Draining the monster",
    "Draining the poisons from the building",
    "Driving the skin bus",
    "Dry humping the ottoman",
    "Dundering the devil-dolphin",
    "Electing the president",
    "Engaging in safe sex",
    "Escorting the one-eyed postal worker out of its denim cell",
    "Faxing Jimmy Dean",
    "Faxing the Pope",
    "Feeding the ducks",
    "Firing the flesh musket",
    "Firing the Surgeon General",
    "Fishing for zipper trout",
    "Fisting my mister",
    "Some Five-finger solo",
    "Five-knuckle-shuffle on the old piss pump",
    "A Little Five on one",
    "Flicking on over the thumb",
    "Flapping Takkie ",
    "Flaying the Emperor",
    "Flicking the bic",
    "Flipping the Bishop",
    "Flogging the bishop",
    "Flogging the dog",
    "Flogging the dolphin",
    "Flogging the dong",
    "Flogging the frog",
    "Flogging the hog",
    "Flogging the log",
    "Flogging the mule",
    "Flogging the salami",
    "Flogging my dumber brother",
    "A Flute solo",
    "Fly fishing",
    "Fondling the fig",
    "Freeing Willy",
    "Frosting the pastries",
    "Galloping the antelope",
    "Galloping the old lizard",
    "Genitalic stimulation via phallengetic motion",
    "Getting a date with Slick Mittens",
    "Getting a grip on things",
    "Getting a stiffy",
    "Getting chafed",
    "Getting off",
    "Getting the German soldier marching",
    "Getting the glue stick",
    "Getting to know myself",
    "Getting my palm read by Mister Softee",
    "Getting my palm red",
    "Getting my pole varnished",
    "Giving it a tug",
    "Giving myself a low five",
    "Glazing the donut",
    "Going a couple of rounds with ol' josh",
    "Going blind",
    "Going on a date with Handrea and Palmela",
    "Going on a date with Rosey Palm and the five daughters",
    "Going on Peewee's little adventure",
    "Grappling the gorilla",
    "Greasing the pipe",
    "Gripping the pencil",
    "Hacking the hog",
    "Hand Shandy",
    "Handy work",
    "Hanging the old man",
    "Hard labor",
    "Having a ball",
    "Having a conversation with the one-eyed trouser snake",
    "Having a date with Fisty Palmer",
    "Having a date with Rosie Palm and her five sisters",
    "Having a ham shank",
    "Having a J. Arthur",
    "Having a one-night-stand with myself",
    "Having a Sherman",
    "Having a tug",
    "Having a tug-of-war with the cyclops",
    "Having an arm-wrestle with my one-eyed vessel",
    "Having dinner",
    "Having it off",
    "Having sex with someone you love",
    "Hitchhiking to heaven",
    "Hitchhiking underneath the big top",
    "Holding my own",
    "Holding the sausage hostage",
    "Honing the cone",
    "Hugging the hog",
    "Humping the hose",
    "Ironing some wrinkles",
    "Jack hammering",
    "Jacking off",
    "Jazzing myself",
    "Jerkin' the gherkin",
    "Jerking Jamby",
    "Jerking off",
    "Jerking the turkey",
    "Jerking yanking daisy-chaining",
    "Jizzlobbing",
    "Juggling the coullions",
    "Just jerkin' it",
    "Kicking seamen",
    "Kicking my roommate out for five to ten minutes to 'call my parents'",
    "Killing it",
    "Kneading my knockwurst.",
    "Knuckle shuffle on the ol' piss pump",
    "Knuckling the bone",
    "La veuve poignet",
    "Launching the hand shuttle",
    "Looking for ticks",
    "Loping the mule",
    "Loving the muppet",
    "Lubing the Tube",
    "Making a foreskin cone",
    "Making friends with Big Ed",
    "Making instant pudding",
    "Making the bald man puke",
    "Making the scene with the magazine",
    "Making vanilla jism shakes",
    "Making myself at home",
    "Mangling the midget",
    "Manipulating the mango",
    "Manning the cockpit",
    "Manual labor",
    "Manual override",
    "Master bacon",
    "Meeting Mary Palm and her five sisters",
    "Meeting Rosie Hancock",
    "Meeting with Mother Thumb and her four daughters",
    "Milking one's self",
    "Milking the bull",
    "Milking the cow",
    "Milking the lizard",
    "Milking the moose",
    "Milking the weasel",
    "Minding my own business",
    "Molesting the mole",
    "Mounting a corporal and four",
    "Much goo about nothing",
    "Nerking my throbber",
    "Oiling the glove",
    "Onan's Olympics",
    "Onanism",
    "Blasting a One gun salute",
    "A One man show",
    "One off the wrist",
    "Packing my palm",
    "Paddling the pickle",
    "Painting the ceiling",
    "Painting the pickle",
    "Painting the walls",
    "Palming the calm",
    "Peelin' some chiles",
    "Peeling the banana",
    "Peeling the carrot",
    "Performing a self-test",
    "Performing diagnostics on my ManTool",
    "Perling the oyster",
    "Petting the lizard",
    "Phoning the czar",
    "Pipping the pumpkin",
    "Playing a little five-on-one",
    "Playing a one-stringed guitar",
    "Playing in a one-man show",
    "Playing Peek-A-Boo With Mr. Johnson",
    "Playing peekaboo",
    "Playing pocket pinball",
    "Playing pocket pool",
    "Playing tag with the pink torpedo",
    "Playing the flesh flute",
    "Playing the one-stringed melody",
    "Playing the skin flute",
    "Playing tug-o-war with the cyclops",
    "Playing Uno",
    "Playing with the spitting llama",
    "Playing with my turtle",
    "Pleasing my pisser",
    "Plunking my twanger",
    "Some Pocket pinball",
    "Some Pocket pool",
    "Pole vaulting",
    "Polishing Percy in my palm",
    "Polishing the beak",
    "Polishing the family jewels",
    "Polishing the helmet",
    "Polishing the rocket",
    "Polishing the sword",
    "Popping a nut",
    "Popping the cork",
    "Pounding off",
    "Pounding the bald-headed moose",
    "Pounding the pud",
    "Pounding my flounder",
    "Preparing the carrot",
    "Priming the pump",
    "Pud wrestling",
    "Pulling off",
    "Pulling rank",
    "Pulling the bologna pony",
    "Pulling the carrot",
    "Pulling the Colonel Sanders Heimleich Manuever",
    "Pulling the cord",
    "Pulling the five-knuckle shuffle",
    "Pulling the goalie",
    "Pulling the handbrake",
    "Pulling the pole",
    "Pulling the Pope",
    "Pulling the weed",
    "Pulling the wire",
    "Pulling my goalie",
    "Pulling my own leg",
    "Pulling my prick",
    "Pulling my pud",
    "Pulling my taffy",
    "Pummeling the priest",
    "Pumping cream",
    "Pumping the electric goo gun",
    "Pumping the gas at the self-service island",
    "Pumping the python",
    "Pumping the stump",
    "Punchin' the munchkin",
    "Punching the clown",
    "Punching the munchin",
    "Punishing Percy in the palm",
    "Punishing the Pope",
    "Qualifying in the testicular time trial",
    "Raising the mainsail",
    "Ramming the ham",
    "Rapid one arm pull-ups",
    "Reading poetry",
    "Relieving tension",
    "Riding the great white knuckler",
    "Rolling my own",
    "Romancing the bone",
    "Romeo and Himself",
    "Roping the pony",
    "Roping the Pope",
    "Roughing up the suspect",
    "Rubbing off",
    "Rubbing one out",
    "Rubbing the magic one-eyed wonder weasel",
    "Rubbing the pink eraser",
    "Rubbing the rod",
    "Running off a batch by hand",
    "Running the cheeta",
    "Sacrificing sperm to the god of lonely nights",
    "Sanding wood",
    "Saying a private prayer in the Church of the First Holy Monkey",
    "playing Schnauzer Shuffleboard",
    "Scouring the tower of power",
    "Scraping my horn",
    "Scratchin the itch",
    "Se faire les cinq doigts de la main",
    "A Secret handshake",
    "Engaging in Self abuse",
    "A little Self-induced penile regurgitation",
    "Some Self-inflicted intercourse",
    "Shaking hands with Abraham Lincoln",
    "Shaking hands with Jack McNasty",
    "Shaking hands with Mr. Happy",
    "Shaking Hands with Mr. President",
    "Shaking hands with the general",
    "Shaking hands with the midget",
    "Shaking hands with the unemployed",
    "Shaking hands with the wife's best friend",
    "Shaking hands with my John Thomas",
    "Shaking hands with my wife's best friend",
    "Shaking hands with Yul Brenner",
    "Shaking the bottle",
    "Shaking the dice",
    "Shaking the hand of the self-employed",
    "Shaking the sauce",
    "Shaking the sausage",
    "Shaking the snake",
    "Shanking",
    "Shellacking the shellaleigh",
    "Shemping the hog",
    "Shifting gears",
    "Shining the helmet",
    "Shining the pork sword",
    "Shining my pole",
    "Shooting skeet",
    "Shooting flies",
    "Shooting for the moon",
    "Shooting putty at the moon",
    "Shooting tadpoles at the moon",
    "Shooting my wad",
    "Shucking my corn",
    "Slaking the bacon",
    "Slamming the ham",
    "Slamming the hammer",
    "Slamming the salami",
    "Slamming the salmon",
    "Slamming the spam",
    "Slapping the big-nosed Rasta man",
    "Slappin the purple headed yogurt pistol",
    "Slapping high fives with Yul Brynner",
    "Slapping it",
    "Slapping pappy",
    "Slapping the carrot",
    "Slapping the clown",
    "Slapping the donkey",
    "Slapping the FleshGopher",
    "Slapping the pud",
    "Slapping the salami",
    "Slinging the jelly",
    "Smacking the oompa loompa",
    "Smacking the salami",
    "Smacking the weasel",
    "Smacking-off",
    "Snapping one off",
    "Snapping the carrot",
    "Snapping the monkey",
    "Snapping the rubber",
    "Snapping the whip",
    "A Solo flight",
    "A Solo marathon",
    "Some Solo sex",
    "Spanking Cheetah",
    "Spanking Elvis",
    "Spanking Frank",
    "Spanking the bishop",
    "Spanking the monkey",
    "Spanking the salami",
    "Spanking the wank",
    "Spit-polishing the purple helmet",
    "Spunking",
    "Squeezing the cheese",
    "Squeezing the cream from the flesh Twinkie",
    "Squeezing the juice",
    "Squeezing the lemon",
    "Squeezing the weasel",
    "Squeezing my cheese-dog",
    "A little Stinky pinky",
    "Stirring the batter",
    "Stirring the yogurt",
    "Strainin' the main vein",
    "Strangling the Serpent",
    "Striking the pink match",
    "Stroking it",
    "Stroking off",
    "Stroking the dog",
    "Stroking the lizard",
    "Stroking the mole",
    "Stroking the one-eyed burping gecko",
    "Stroking the satin-headed serpent",
    "Stroking the squirmin' German",
    "Stroking the wiener",
    "Stroking my poker",
    "Stroking my twinkie",
    "Taking a nap",
    "Taking a shake break",
    "Taking Herman to the circus",
    "Taking matters into my own hands",
    "Taking ol' one eye through the fly",
    "Taking part in population control",
    "Taking some time off",
    "Taking the Jocelyn Elders Midterm",
    "Taking the monster for a one-armed ride",
    "Talking quietly to myself",
    "Taming the shrew",
    "Taunting the one-eyed weasel",
    "Teasing the weasel",
    "Teasing the weenie",
    "Tenderizing the meat",
    "Tenderizing the tube steak",
    "A Testicular tensile strength test",
    "Testing the testicles",
    "Testing my batteries",
    "That crazy hand jive",
    "The art of Unisex",
    "The Colonel Sanders Heimleich Maneuver",
    "The five knuckle shuffle on the old piss pipe",
    "Thrapping",
    "Throwing",
    "Throwing one",
    "Thumping the pump",
    "Ticklewigglejigglepickle",
    "Tickling my fancy",
    "Tickling the ivory",
    "Tickling the one-eyed weasel",
    "Tickling the pickle",
    "Tonking",
    "Torkin' the fork",
    "Torturing the tentacle",
    "Tossing off",
    "Tossing the salad",
    "Tossing the snag",
    "Tossing the turkey",
    "Tossing yogurt",
    "Treating myself right",
    "Trouser snake CPR",
    "Tugging the slug",
    "Tugging the tapioca tube",
    "Tuning my horn",
    "Turning Japanese",
    "Twanging the wire",
    "Tweaking my twinkie",
    "Twisting my crank",
    "Twisting my tool",
    "Unloading the gun",
    "Using the Force on Darth Vader",
    "Varnishing the flagpole",
    "Violating the hedge-hog",
    "Visiting Rosy Palm and her five daughters",
    "Wacking off",
    "Wacking the one-eyed worm",
    "Wacking the weasel",
    "Wacking the willie",
    "Waking the dead",
    "Waking Wee Willie Wonka",
    "Walking the dog",
    "Walking the plank",
    "Walking the snake",
    "Waltzing with Willy",
    "Wanking",
    "Wanking with the one-eyed wonder weasel",
    "Washing the meat",
    "Waving the Magic Wand",
    "Waxing the car",
    "Waxing the carrot",
    "Waxing the dolphin",
    "Waxing my surfboard",
    "Whackin the weasel",
    "Whacking it",
    "Whacking off",
    "Whacking Willy",
    "Whipping off",
    "Whipping the bishop",
    "Whipping the dummy",
    "Whipping the one-eyed trouser snake",
    "Whipping the rat",
    "Whipping the stiff",
    "Whipping the wire",
    "Whipping up some sour cream",
    "Whipping willy the one-eyed wonder-worm",
    "Whipping my dripper",
    "White-water wristing",
    "Whittling the stick",
    "Whizzing jism",
    "Windsurfing on Mount Baldy",
    "Wonking my conker",
    "Wonking my donk",
    "Workin' out a stiff joint",
    "Working off",
    "Working off a batch",
    "Wrestling the eel",
    "Wrestling the one-eyed monster",
    "Wrestling the purple headed warrior",
    "Wrestling with the bald champ",
    "Wringing out my rope",
    "doing Wrist aerobics",
    "Yanking off",
    "Yanking the crank",
    "Yanking the yoyo",
    "Yanking my plank",
    "Boxing my clown",
    "Punching the munchkin",
    "Wanking",
    "Polishing my sword",
    "Some Backstroke roulette",
    "Bashing the candle",
    "Tipping off the inspector",
    "Tossing the snag",
    "Tossing the turkey",
    "Tossing yogurt",
    "Tugging the slug",
    "Twanging the wire",
    "Tweaking my Twinkie",
    "Twisting my crank",
    "Unleashing the alabaster yak",
    "Unloading the gun",
    "Unpacking the moving van",
    "Varnishing the flagpole",
    "Varnishing the banister",
    "Visiting with Papa Smurf",
    "Waking the dead",
    "Walking the dog",
    "Walking the plank",
    "Walking a mile in Mr. Wiggly’s shoes",
    "Wallowing in self pity",
    "Wanking with the one-eyed wonder weasel",
    "Washing the meat",
    "Waxing the Buick",
    "Waxing the carrot",
    "Waxing the dolphin",
    "Waxin’ n’ Milkin’",
    "Whacking it",
    "Whacking the weasel",
    "Whacking my Willy",
    "Whipping the dummy",
    "Whipping the one-eyed trouser snake",
    "Whipping the one-eyed worm",
    "Whipping the rat",
    "Whipping the stiff",
    "Whipping the wire",
    "Whipping up some sour cream",
    "Whipping my dripper",
    "Whitewashing with Huck and Tom",
    "Whittling the stick",
    "Wiggling my walrus",
    "Windsurfing on Mount Baldy",
    "Wonking my conker",
    "Working things out",
    "Working at my own speed",
    "Working late at the office",
    "Working up a foamy lather",
    "Working without Annette",
    "Wrestling the dragon",
    "Wrestling the eel",
    "Wrestling with the bald champ",
    "Wringing out my rope",
    "Some Wrist aerobics",
    "Yanking the crank",
    "Yanking the yo-yo",
    "Yanking my plank",
    "Evicting the testicular squatters",
    "Evicting the testicular squatters",
    "Pooping the pud",
    "Rearranging the deck chairs",
    "Lavishly caressing my own thighs",
    "Spurting into my own hand",
    "Tossing the bagel",
    "Feeding my own dogs",
    "Borrowing Mrs. Frump's bicycle",
    "Riding an automobile",
    "Crushing it to bits",
    "Whipping the beaver",
    "Socking myself in the face with the duster!",
    "Stroking my flabby gut with my belly button lint filter",
    "Warming my bumblebee hive in its nest",
    "Flattening the pillow",
    "Snatching back my hand and going 'I told you so'",
    "Scalding my own back yard",
    "Lacing up the white sneakers",
    "Bouncing the cat",
    "Punching myself in the nose",
    "Lying on the lavender pillows",
    "Thawing the goose on a saran wrap",
    "Whipping the wimp",
    "Cobbal-binging the cussword",
    "Smelling my shirt collar on a rainy day",
    "Nailing my best friend to the shed to rot",
    "Screwing the scullery maid",
    "Blowing up the big red one",
    "Flipping the pork pie",
    "Squirting some mustardy",
    "Sinking fast on this one",
    "Smacking the toaster",
    "Tossing potatoes on high alert",
    "Making the money work",
    "Flexing my ham hock",
    "Busting a gut and going for a walk on Mars",
    "Mucking the meter",
    "Going in and seeing a lady doctor named Miss Jane for the old lady cure",
    "Playing doctor",
    "Making her a man again",
    "Making a meal out of it",
    "Rolling around on a spongecake of cocaine",
    "Catching the canary",
    "Being a chicken wing",
    "Squeezefucking",
    "Cracking a safe",
    "Rubbing one's tuchus",
    "Gulping the goop",
    "Conducting the orchestra",
    "Beef-a-rooneying",
    "Rubbing one's tuchus",
    "Carrying my balsam root to hell",
    "Feeding the chicken",
    "Going out shopping with myself",
    "Frownie, go fishing",
    "Winkie, go dancing",
    "Pretzel face face, make it snuggly snortable facey go go go",
    "Shakin', a shaking' hand from a shake",
    "A jingaling and a singaling from my lips",
    "Whipping and wringing with its little hand",
    "One little finger to pinch one little tinge. YIPPee!",
    "Rubbing the borsalino.",
    "Yawning over yon bonfire on my tail",
    "Rising with my right hand my friend. You're at my behest. And in a minute, you can waddle on up the shore, a bit faster too you wannit be...",
    "And wah, my dung shall fly as thy name calls me home again?",
    "Blowing myself silly without having the courage to touch myself",
    "Sliding an elbow with one-legged Bob, a maimed-from-behind lover",
    "Sailing on the high seas",
    "Tucking Tinky-Tinky into bed",
    "Squashing my pride",
    "Fending off the flys on the toilet",
    "Feeding the hunk-o-meat, that sweet hunk-o-meat",
    "Feeding the pigeons",
    "Feeding my wacky friend, squirrel-style (tiny but perfectly edible morsel)",
    "Slapping the purple cow's milk bag",
    "Gentle massaging for the ladybug ladybot (but don't let her bite)",
    "Facing my true colors",
    "Fingeling my finicky fizzbuckets",
    "Bending the knee to the great cheese curds of lore for the next one million zillion billion billion years",
]